"""
Default Courses API — AI-generated platform-wide courses available to every
role EXCEPT student (independent trader, faculty, institution_admin, admin).
Students have their own separate Academy (routes/student_academy.py).

A fixed ordered list of course topics is seeded on first request (if not
already present). Each course's lesson content and quiz are generated by
Groq lazily, the first time a user opens it, then persisted — generation
never repeats. Courses unlock sequentially: course N+1 stays locked until
every lesson in course N is marked complete and its quiz is passed.

Reuses the same timer/proctoring/one-attempt assessment mechanics as the
student Academy (see routes/student_academy.py) — same rules, same shapes,
just gated to a different set of roles.
"""

import logging
from datetime import datetime, timezone, timedelta
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field
from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession

from database.connection import get_db
from models.user import User
from models.course import (
    Course, Lesson, Assessment, Question, Choice,
    LessonProgress, AssessmentAttempt, AttemptAnswer,
)
from dependencies.non_student import require_non_student
from services.invite_service import _as_uuid, _as_aware_utc
from services.default_course_ai import generate_default_course_content, DefaultCourseAIError

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/default-courses", tags=["Default Courses"])

SECONDS_PER_QUESTION = 60

# Fixed ordered topic list — seeded once, content generated lazily per course.
DEFAULT_COURSE_TOPICS = [
    {"title": "Stock Market Basics", "description": "What stocks are, how NSE/BSE work, and how prices move."},
    {"title": "Reading a Candlestick Chart", "description": "Candle anatomy, timeframes, and basic price-action patterns."},
    {"title": "Risk Management Essentials", "description": "Position sizing, stop-loss placement, and protecting capital."},
    {"title": "Understanding Options Basics", "description": "Calls, puts, premiums, and why options carry more risk."},
    {"title": "Futures Trading Fundamentals", "description": "Margin, leverage, and how futures contracts work."},
    {"title": "Building a Trading Plan", "description": "Entry/exit rules, journaling, and avoiding emotional trades."},
]


class SubmitAnswerInput(BaseModel):
    question_id: str
    choice_id: Optional[str] = None


class SubmitAttemptRequest(BaseModel):
    answers: list[SubmitAnswerInput] = Field(default_factory=list)
    attempt_id: str
    flagged: bool = False
    flag_reason: Optional[str] = None


async def _ensure_seeded(db: AsyncSession):
    """Creates the fixed default-course rows (title/description only,
    status=approved, is_default=true) if they don't exist yet."""
    existing_result = await db.execute(select(func.count(Course.id)).where(Course.is_default.is_(True)))
    if (existing_result.scalar() or 0) > 0:
        return

    for idx, topic in enumerate(DEFAULT_COURSE_TOPICS):
        db.add(Course(
            institution_id=None,
            created_by_user_id=None,
            title=topic["title"],
            description=topic["description"],
            status="approved",
            is_default=True,
            default_order_index=idx,
            content_generated=False,
        ))
    await db.commit()


async def _get_own_attempt(db: AsyncSession, user: User, assessment_id) -> Optional[AssessmentAttempt]:
    result = await db.execute(
        select(AssessmentAttempt)
        .where(AssessmentAttempt.user_id == user.id, AssessmentAttempt.assessment_id == assessment_id)
        .order_by(AssessmentAttempt.started_at.desc())
    )
    return result.scalars().first()


async def _get_default_course(db: AsyncSession, course_id: str) -> Course:
    course_uuid = _as_uuid(course_id)
    course = await db.get(Course, course_uuid) if course_uuid else None
    if not course or not course.is_default:
        raise HTTPException(status_code=404, detail="Course not found")
    return course


async def _course_is_complete(db: AsyncSession, user: User, course: Course) -> bool:
    lesson_ids_result = await db.execute(select(Lesson.id).where(Lesson.course_id == course.id))
    lesson_ids = [row[0] for row in lesson_ids_result.all()]
    if not lesson_ids:
        return False

    completed_result = await db.execute(
        select(func.count(LessonProgress.id)).where(
            LessonProgress.user_id == user.id, LessonProgress.lesson_id.in_(lesson_ids)
        )
    )
    if (completed_result.scalar() or 0) < len(lesson_ids):
        return False

    assessment_result = await db.execute(select(Assessment).where(Assessment.course_id == course.id))
    assessment = assessment_result.scalars().first()
    if not assessment:
        return True

    attempt = await _get_own_attempt(db, user, assessment.id)
    return bool(attempt and attempt.passed)


async def _generate_and_persist_content(db: AsyncSession, course: Course):
    try:
        generated = await generate_default_course_content(course.title, course.description or "")
    except DefaultCourseAIError as exc:
        raise HTTPException(status_code=503, detail=str(exc))

    for idx, lesson_data in enumerate(generated["lessons"]):
        db.add(Lesson(course_id=course.id, title=lesson_data["title"], content=lesson_data["content"], order_index=idx))

    quiz = generated["quiz"]
    if quiz["questions"]:
        assessment = Assessment(
            course_id=course.id,
            title=quiz["title"],
            pass_score=quiz["pass_score"],
            question_count=len(quiz["questions"]),
            difficulty="medium",
        )
        db.add(assessment)
        await db.flush()

        for q_idx, q in enumerate(quiz["questions"]):
            question = Question(assessment_id=assessment.id, text=q["text"], order_index=q_idx, source="ai")
            db.add(question)
            await db.flush()
            for c_idx, choice in enumerate(q["choices"]):
                db.add(Choice(question_id=question.id, text=choice["text"], is_correct=choice["is_correct"], order_index=c_idx))

    course.content_generated = True
    await db.commit()


@router.get("/courses")
async def list_default_courses(
    user: User = Depends(require_non_student),
    db: AsyncSession = Depends(get_db),
):
    await _ensure_seeded(db)

    result = await db.execute(
        select(Course).where(Course.is_default.is_(True)).order_by(Course.default_order_index)
    )
    courses = result.scalars().all()
    if not courses:
        return {"courses": []}

    course_ids = [c.id for c in courses]
    lesson_counts = {row[0]: row[1] for row in (await db.execute(
        select(Lesson.course_id, func.count(Lesson.id)).where(Lesson.course_id.in_(course_ids)).group_by(Lesson.course_id)
    )).all()}
    completed_lessons = {row[0]: row[1] for row in (await db.execute(
        select(LessonProgress.course_id, func.count(LessonProgress.id))
        .where(LessonProgress.user_id == user.id, LessonProgress.course_id.in_(course_ids))
        .group_by(LessonProgress.course_id)
    )).all()}

    # Determine unlock state sequentially: a course is unlocked once every
    # prior course in default_order_index has been fully completed.
    out = []
    unlocked_so_far = True
    for course in courses:
        completed = await _course_is_complete(db, user, course) if course.content_generated else False
        state = "locked"
        if unlocked_so_far:
            state = "completed" if completed else "unlocked"
        out.append({
            "id": str(course.id),
            "title": course.title,
            "description": course.description,
            "order_index": course.default_order_index,
            "lesson_count": lesson_counts.get(course.id, 0),
            "lessons_completed": completed_lessons.get(course.id, 0),
            "content_generated": course.content_generated,
            "state": state,
        })
        if not completed:
            unlocked_so_far = False

    return {"courses": out}


@router.get("/courses/{course_id}")
async def get_default_course_detail(
    course_id: str,
    user: User = Depends(require_non_student),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_default_course(db, course_id)

    if not course.content_generated:
        await _generate_and_persist_content(db, course)
        await db.refresh(course)

    lessons_result = await db.execute(
        select(Lesson).where(Lesson.course_id == course.id).order_by(Lesson.order_index, Lesson.created_at)
    )
    lessons = lessons_result.scalars().all()

    progress_result = await db.execute(
        select(LessonProgress.lesson_id).where(LessonProgress.user_id == user.id, LessonProgress.course_id == course.id)
    )
    completed_lesson_ids = {row[0] for row in progress_result.all()}

    assessment_result = await db.execute(select(Assessment).where(Assessment.course_id == course.id))
    assessment = assessment_result.scalars().first()

    assessment_out = None
    if assessment:
        question_count_result = await db.execute(select(func.count(Question.id)).where(Question.assessment_id == assessment.id))
        question_count = question_count_result.scalar() or 0
        attempt = await _get_own_attempt(db, user, assessment.id)
        assessment_out = {
            "id": str(assessment.id),
            "title": assessment.title,
            "pass_score": assessment.pass_score,
            "question_count": question_count,
            "time_limit_seconds": question_count * SECONDS_PER_QUESTION,
            "last_attempt": (
                {
                    "score_percent": attempt.score_percent,
                    "passed": attempt.passed,
                    "flagged": attempt.flagged,
                }
                if attempt else None
            ),
            "locked": bool(attempt),
        }

    return {
        "id": str(course.id),
        "title": course.title,
        "description": course.description,
        "lessons": [
            {
                "id": str(l.id),
                "title": l.title,
                "content": l.content,
                "completed": l.id in completed_lesson_ids,
            }
            for l in lessons
        ],
        "assessment": assessment_out,
    }


@router.post("/courses/{course_id}/lessons/{lesson_id}/complete")
async def mark_lesson_complete(
    course_id: str,
    lesson_id: str,
    user: User = Depends(require_non_student),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_default_course(db, course_id)
    lesson_uuid = _as_uuid(lesson_id)
    lesson = await db.get(Lesson, lesson_uuid) if lesson_uuid else None
    if not lesson or lesson.course_id != course.id:
        raise HTTPException(status_code=404, detail="Lesson not found")

    existing_result = await db.execute(
        select(LessonProgress).where(LessonProgress.user_id == user.id, LessonProgress.lesson_id == lesson.id)
    )
    if not existing_result.scalar_one_or_none():
        db.add(LessonProgress(user_id=user.id, lesson_id=lesson.id, course_id=course.id))
        await db.commit()

    return {"success": True}


@router.get("/courses/{course_id}/assessments/{assessment_id}/take")
async def start_assessment(
    course_id: str,
    assessment_id: str,
    user: User = Depends(require_non_student),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_default_course(db, course_id)
    assessment_uuid = _as_uuid(assessment_id)
    assessment = await db.get(Assessment, assessment_uuid) if assessment_uuid else None
    if not assessment or assessment.course_id != course.id:
        raise HTTPException(status_code=404, detail="Assessment not found")

    existing = await _get_own_attempt(db, user, assessment.id)
    if existing:
        raise HTTPException(status_code=403, detail="You've already taken this quiz.")

    questions_result = await db.execute(
        select(Question).where(Question.assessment_id == assessment.id).order_by(Question.order_index, Question.created_at)
    )
    questions = questions_result.scalars().all()
    if not questions:
        raise HTTPException(status_code=400, detail="This assessment has no questions yet")

    question_ids = [q.id for q in questions]
    choices_result = await db.execute(select(Choice).where(Choice.question_id.in_(question_ids)))
    choices_by_question: dict = {}
    for c in choices_result.scalars().all():
        choices_by_question.setdefault(c.question_id, []).append(c)

    attempt = AssessmentAttempt(
        user_id=user.id,
        assessment_id=assessment.id,
        course_id=course.id,
        score_percent=0,
        passed=False,
        total_questions=len(questions),
        correct_count=0,
    )
    db.add(attempt)
    await db.commit()
    await db.refresh(attempt)

    time_limit_seconds = len(questions) * SECONDS_PER_QUESTION
    started_at = _as_aware_utc(attempt.started_at) or datetime.now(timezone.utc)
    expires_at = started_at + timedelta(seconds=time_limit_seconds)

    return {
        "attempt_id": str(attempt.id),
        "assessment": {
            "id": str(assessment.id),
            "title": assessment.title,
            "pass_score": assessment.pass_score,
        },
        "time_limit_seconds": time_limit_seconds,
        "expires_at": expires_at.isoformat(),
        "questions": [
            {
                "id": str(q.id),
                "text": q.text,
                "choices": [
                    {"id": str(c.id), "text": c.text}
                    for c in sorted(choices_by_question.get(q.id, []), key=lambda c: c.order_index)
                ],
            }
            for q in questions
        ],
    }


@router.post("/courses/{course_id}/assessments/{assessment_id}/submit")
async def submit_assessment(
    course_id: str,
    assessment_id: str,
    req: SubmitAttemptRequest,
    user: User = Depends(require_non_student),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_default_course(db, course_id)
    assessment_uuid = _as_uuid(assessment_id)
    assessment = await db.get(Assessment, assessment_uuid) if assessment_uuid else None
    if not assessment or assessment.course_id != course.id:
        raise HTTPException(status_code=404, detail="Assessment not found")

    attempt_uuid = _as_uuid(req.attempt_id)
    attempt = await db.get(AssessmentAttempt, attempt_uuid) if attempt_uuid else None
    if not attempt or attempt.user_id != user.id or attempt.assessment_id != assessment.id:
        raise HTTPException(status_code=404, detail="Attempt not found")

    questions_result = await db.execute(select(Question).where(Question.assessment_id == assessment.id))
    questions = questions_result.scalars().all()
    if not questions:
        raise HTTPException(status_code=400, detail="This assessment has no questions yet")

    question_ids = [q.id for q in questions]
    choices_result = await db.execute(select(Choice).where(Choice.question_id.in_(question_ids)))
    all_choices = choices_result.scalars().all()
    correct_choice_by_question = {}
    for c in all_choices:
        if c.is_correct:
            correct_choice_by_question[c.question_id] = c.id

    submitted_by_question = {_as_uuid(a.question_id): _as_uuid(a.choice_id) for a in req.answers}

    correct_count = 0
    answer_rows = []
    for q in questions:
        submitted_choice_id = submitted_by_question.get(q.id)
        is_correct = submitted_choice_id is not None and submitted_choice_id == correct_choice_by_question.get(q.id)
        if is_correct:
            correct_count += 1
        answer_rows.append((q.id, submitted_choice_id, is_correct))

    total = len(questions)
    score_percent = round((correct_count / total) * 100) if total else 0
    passed = score_percent >= assessment.pass_score and not req.flagged

    attempt.score_percent = score_percent
    attempt.passed = passed
    attempt.correct_count = correct_count
    attempt.flagged = req.flagged
    attempt.flag_reason = req.flag_reason

    for question_id, choice_id, is_correct in answer_rows:
        db.add(AttemptAnswer(attempt_id=attempt.id, question_id=question_id, choice_id=choice_id, is_correct=is_correct))

    await db.commit()

    return {
        "score_percent": score_percent,
        "passed": passed,
        "flagged": req.flagged,
        "correct_count": correct_count,
        "total_questions": total,
        "pass_score": assessment.pass_score,
    }
