"""
Faculty Course Builder API — scoped strictly to the caller's own institution
and their own authored courses.

A faculty member uploads a course (status="pending"); it is only visible to
students once their Institution Admin approves it (see routes/institution_admin.py).
Faculty can always see and edit their own courses regardless of status, but
never another faculty member's courses. Once approved, a course's content
locks — edits require the Institution Admin.

Lessons may carry one uploaded material file (PDF/DOCX/PPTX/MD); its text is
extracted and stored so it can be used as AI context for MCQ generation.
Assessments hold structured multiple-choice Questions/Choices, added either
manually or generated by AI from the course's lesson material.
"""

import logging
import os
import uuid
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, UploadFile, File
from pydantic import BaseModel, Field
from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession

from database.connection import get_db
from models.user import User
from models.course import Course, Lesson, LessonMaterial, Assessment, Question, Choice
from dependencies.faculty import require_faculty
from services.invite_service import _as_uuid
from services import text_extraction
from services.assessment_ai import generate_mcq_questions, AssessmentAIError
from config.groq_assessment_config import groq_assessment_config

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/faculty", tags=["Faculty"])


def _iso(val):
    if val is None:
        return None
    if isinstance(val, str):
        return val
    if hasattr(val, "isoformat"):
        return val.isoformat()
    return str(val)


# ── Lesson material upload config ───────────────────────────────
UPLOAD_DIR = "uploads/lesson-materials"
os.makedirs(UPLOAD_DIR, exist_ok=True)

ALLOWED_FILE_TYPES = {
    "application/pdf": "pdf",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "docx",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": "pptx",
    "text/markdown": "md",
    "text/plain": "md",
}
MAX_FILE_SIZE_BYTES = 20 * 1024 * 1024  # 20MB


# ── Pydantic models ───────────────────────────────────────────

class CreateCourseRequest(BaseModel):
    title: str = Field(min_length=1, max_length=200)
    description: Optional[str] = None


class UpdateCourseRequest(BaseModel):
    title: Optional[str] = Field(default=None, min_length=1, max_length=200)
    description: Optional[str] = None


class CreateLessonRequest(BaseModel):
    title: str = Field(min_length=1, max_length=200)
    content: Optional[str] = None
    order_index: int = 0


LessonRequest = CreateLessonRequest


class UpdateLessonRequest(BaseModel):
    title: Optional[str] = Field(default=None, min_length=1, max_length=200)
    content: Optional[str] = None
    order_index: Optional[int] = None


class CreateAssessmentRequest(BaseModel):
    title: str = Field(min_length=1, max_length=200)
    instructions: Optional[str] = None
    pass_score: int = Field(default=70, ge=0, le=100)
    question_count: int = Field(default=5, ge=1, le=50)
    difficulty: str = Field(default="medium")
    lesson_ids: Optional[list[str]] = None


AssessmentConfigRequest = CreateAssessmentRequest


class UpdateAssessmentRequest(BaseModel):
    title: Optional[str] = Field(default=None, min_length=1, max_length=200)
    instructions: Optional[str] = None
    pass_score: Optional[int] = Field(default=None, ge=0, le=100)
    question_count: Optional[int] = Field(default=None, ge=1, le=50)
    difficulty: Optional[str] = None
    lesson_ids: Optional[list[str]] = None


class ChoiceInput(BaseModel):
    text: str = Field(min_length=1)
    is_correct: bool = False


class CreateQuestionRequest(BaseModel):
    text: str = Field(min_length=1)
    choices: list[ChoiceInput] = Field(min_length=2, max_length=6)


ManualQuestionRequest = CreateQuestionRequest


class GenerateQuestionsRequest(BaseModel):
    pass  # uses the assessment's own stored question_count/difficulty config


def _course_out(course: Course, lesson_count: int = 0, assessment_count: int = 0) -> dict:
    return {
        "id": str(course.id),
        "title": course.title,
        "description": course.description,
        "status": course.status,
        "review_note": course.review_note,
        "reviewed_at": _iso(course.reviewed_at),
        "lesson_count": lesson_count,
        "assessment_count": assessment_count,
        "created_at": _iso(course.created_at),
        "updated_at": _iso(course.updated_at),
    }


def _lesson_out(lesson: Lesson, materials: list = None) -> dict:
    return {
        "id": str(lesson.id),
        "title": lesson.title,
        "content": lesson.content,
        "order_index": lesson.order_index,
        "file_url": lesson.file_url,
        "file_name": lesson.file_name,
        "file_type": lesson.file_type,
        "has_extracted_text": bool(lesson.extracted_text),
        "materials": materials or (
            [
                {
                    "id": f"primary-{lesson.id}",
                    "file_url": lesson.file_url,
                    "file_name": lesson.file_name,
                    "file_type": lesson.file_type,
                    "has_extracted_text": bool(lesson.extracted_text),
                }
            ] if lesson.file_url else []
        ),
    }


def _question_out(question: Question, choices: list[Choice]) -> dict:
    return {
        "id": str(question.id),
        "text": question.text,
        "source": question.source,
        "order_index": question.order_index,
        "choices": [
            {"id": str(c.id), "text": c.text, "is_correct": c.is_correct, "order_index": c.order_index}
            for c in sorted(choices, key=lambda c: c.order_index)
        ],
    }


def _assessment_out(assessment: Assessment, question_count: int = 0) -> dict:
    return {
        "id": str(assessment.id),
        "title": assessment.title,
        "instructions": assessment.instructions,
        "pass_score": assessment.pass_score,
        "question_count": assessment.question_count,
        "difficulty": assessment.difficulty,
        "lesson_ids": assessment.lesson_ids or [],
        "generated_question_count": question_count,
    }


async def _get_own_course(db: AsyncSession, faculty: User, course_id: str) -> Course:
    course_uuid = _as_uuid(course_id)
    course = await db.get(Course, course_uuid) if course_uuid else None
    if not course or str(course.created_by_user_id) != str(faculty.id):
        raise HTTPException(status_code=404, detail="Course not found")
    return course


def _assert_editable(course: Course):
    # Faculty members can add/edit lessons and assessments even if the course is approved
    pass


async def _get_own_lesson(db: AsyncSession, course: Course, lesson_id: str) -> Lesson:
    lesson_uuid = _as_uuid(lesson_id)
    lesson = await db.get(Lesson, lesson_uuid) if lesson_uuid else None
    if not lesson or str(lesson.course_id) != str(course.id):
        raise HTTPException(status_code=404, detail="Lesson not found")
    return lesson


async def _get_own_assessment(db: AsyncSession, course: Course, assessment_id: str) -> Assessment:
    assessment_uuid = _as_uuid(assessment_id)
    assessment = await db.get(Assessment, assessment_uuid) if assessment_uuid else None
    if not assessment or str(assessment.course_id) != str(course.id):
        raise HTTPException(status_code=404, detail="Assessment not found")
    return assessment


def _lesson_file_path(lesson: Lesson) -> Optional[str]:
    if not lesson.file_url:
        return None
    return lesson.file_url.replace("/uploads/", "uploads/", 1)


# ── Dashboard ─────────────────────────────────────────────────

@router.get("/dashboard")
async def get_faculty_dashboard(
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    counts_result = await db.execute(
        select(Course.status, func.count(Course.id))
        .where(Course.created_by_user_id == faculty.id)
        .group_by(Course.status)
    )
    counts = {status: count for status, count in counts_result.all()}
    return {
        "total_courses": sum(counts.values()),
        "pending": counts.get("pending", 0),
        "approved": counts.get("approved", 0),
        "rejected": counts.get("rejected", 0),
    }


@router.get("/assessment-ai-status")
async def assessment_ai_status(faculty: User = Depends(require_faculty)):
    return {"available": groq_assessment_config.is_configured()}


# ── Courses ───────────────────────────────────────────────────

@router.get("/courses")
async def list_my_courses(
    status: Optional[str] = None,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    filters = [Course.created_by_user_id == faculty.id]
    if status:
        if status not in ("pending", "approved", "rejected"):
            raise HTTPException(status_code=400, detail="Invalid status filter")
        filters.append(Course.status == status)

    result = await db.execute(select(Course).where(*filters).order_by(Course.created_at.desc()))
    courses = result.scalars().all()
    if not courses:
        return {"courses": []}

    course_ids = [c.id for c in courses]
    lesson_counts = {row[0]: row[1] for row in (await db.execute(
        select(Lesson.course_id, func.count(Lesson.id)).where(Lesson.course_id.in_(course_ids)).group_by(Lesson.course_id)
    )).all()}
    assessment_counts = {row[0]: row[1] for row in (await db.execute(
        select(Assessment.course_id, func.count(Assessment.id)).where(Assessment.course_id.in_(course_ids)).group_by(Assessment.course_id)
    )).all()}

    return {
        "courses": [
            _course_out(c, lesson_counts.get(c.id, 0), assessment_counts.get(c.id, 0))
            for c in courses
        ]
    }


@router.post("/courses")
async def create_course(
    req: CreateCourseRequest,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = Course(
        institution_id=faculty.institution_id,  # forced server-side
        created_by_user_id=faculty.id,           # forced server-side
        title=req.title.strip(),
        description=(req.description or "").strip() or None,
        status="pending",
    )
    db.add(course)
    await db.commit()
    await db.refresh(course)
    return _course_out(course)


@router.get("/courses/{course_id}")
async def get_course(
    course_id: str,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)

    lessons_result = await db.execute(
        select(Lesson).where(Lesson.course_id == course.id).order_by(Lesson.order_index, Lesson.created_at)
    )
    lessons = lessons_result.scalars().all()

    assessments_result = await db.execute(
        select(Assessment).where(Assessment.course_id == course.id).order_by(Assessment.created_at)
    )
    assessments = assessments_result.scalars().all()

    question_counts = {}
    if assessments:
        assessment_ids = [a.id for a in assessments]
        question_counts = {row[0]: row[1] for row in (await db.execute(
            select(Question.assessment_id, func.count(Question.id))
            .where(Question.assessment_id.in_(assessment_ids))
            .group_by(Question.assessment_id)
        )).all()}

    lesson_ids = [l.id for l in lessons]
    materials_by_lesson: dict = {}
    if lesson_ids:
        try:
            mats_res = await db.execute(
                select(LessonMaterial).where(LessonMaterial.lesson_id.in_(lesson_ids)).order_by(LessonMaterial.created_at)
            )
            for mat in mats_res.scalars().all():
                materials_by_lesson.setdefault(str(mat.lesson_id), []).append({
                    "id": str(mat.id),
                    "file_url": mat.file_url,
                    "file_name": mat.file_name,
                    "file_type": mat.file_type,
                    "has_extracted_text": bool(mat.extracted_text),
                })
        except Exception as mat_err:
            logger.warning(f"LessonMaterial query warning: {mat_err}")

    return {
        **_course_out(course, len(lessons), len(assessments)),
        "lessons": [
            _lesson_out(
                l,
                materials=materials_by_lesson.get(str(l.id)) or (
                    [
                        {
                            "id": f"primary-{l.id}",
                            "file_url": l.file_url,
                            "file_name": l.file_name,
                            "file_type": l.file_type,
                            "has_extracted_text": bool(l.extracted_text),
                        }
                    ] if l.file_url else []
                )
            )
            for l in lessons
        ],
        "assessments": [_assessment_out(a, question_counts.get(a.id, 0)) for a in assessments],
    }


@router.post("/courses/{course_id}/lessons/{lesson_id}/materials")
async def upload_lesson_material(
    course_id: str,
    lesson_id: str,
    file: UploadFile = File(...),
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)
    _assert_editable(course)
    lesson = await _get_own_lesson(db, course, lesson_id)

    file_type = ALLOWED_FILE_TYPES.get(file.content_type)
    if not file_type:
        fn = file.filename.lower()
        if fn.endswith(".pdf"):
            file_type = "pdf"
        elif fn.endswith(".docx"):
            file_type = "docx"
        elif fn.endswith(".pptx"):
            file_type = "pptx"
        elif fn.endswith(".md"):
            file_type = "md"
        else:
            raise HTTPException(status_code=400, detail="Unsupported file format")

    content_bytes = await file.read()
    if len(content_bytes) > MAX_FILE_SIZE_BYTES:
        raise HTTPException(status_code=400, detail="File size exceeds 20MB limit")

    mat_uuid = uuid.uuid4()
    saved_name = f"{mat_uuid}.{file_type}"
    file_path = os.path.join(UPLOAD_DIR, saved_name)
    with open(file_path, "wb") as f:
        f.write(content_bytes)

    file_url = f"/uploads/lesson-materials/{saved_name}"
    extracted_text = text_extraction.extract_text(file_path, file_type)

    mat = LessonMaterial(
        lesson_id=lesson.id,
        file_url=file_url,
        file_name=file.filename,
        file_type=file_type,
        extracted_text=extracted_text,
    )
    db.add(mat)

    if not lesson.file_url:
        lesson.file_url = file_url
        lesson.file_name = file.filename
        lesson.file_type = file_type
        lesson.extracted_text = extracted_text

    await db.commit()
    await db.refresh(mat)

    return {
        "id": str(mat.id),
        "file_url": mat.file_url,
        "file_name": mat.file_name,
        "file_type": mat.file_type,
        "has_extracted_text": bool(mat.extracted_text),
    }


@router.delete("/courses/{course_id}/lessons/{lesson_id}/materials/{material_id}")
async def delete_lesson_material(
    course_id: str,
    lesson_id: str,
    material_id: str,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)
    _assert_editable(course)
    lesson = await _get_own_lesson(db, course, lesson_id)

    if material_id.startswith("primary-"):
        lesson.file_url = None
        lesson.file_name = None
        lesson.file_type = None
        lesson.extracted_text = None
        await db.commit()
        return {"success": True}

    mat_uuid = _as_uuid(material_id)
    mat = await db.get(LessonMaterial, mat_uuid) if mat_uuid else None
    if not mat or mat.lesson_id != lesson.id:
        raise HTTPException(status_code=404, detail="Material not found")

    await db.delete(mat)
    await db.commit()
    return {"success": True}


@router.post("/courses/{course_id}/assessments/{assessment_id}/regenerate-questions")
async def regenerate_assessment_questions(
    course_id: str,
    assessment_id: str,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)
    _assert_editable(course)
    assessment = await _get_own_assessment(db, course, assessment_id)

    target_uuids = []
    if assessment.lesson_ids and isinstance(assessment.lesson_ids, list):
        target_uuids = [_as_uuid(lid) for lid in assessment.lesson_ids if _as_uuid(lid)]

    if target_uuids:
        lessons_res = await db.execute(select(Lesson).where(Lesson.course_id == course.id, Lesson.id.in_(target_uuids)))
    else:
        lessons_res = await db.execute(select(Lesson).where(Lesson.course_id == course.id))

    lessons = lessons_res.scalars().all()
    lesson_ids = [l.id for l in lessons]

    texts = [f"{l.title}\n{l.content or ''}\n{l.extracted_text or ''}".strip() for l in lessons]
    if lesson_ids:
        try:
            mats_res = await db.execute(select(LessonMaterial.extracted_text).where(LessonMaterial.lesson_id.in_(lesson_ids)))
            texts.extend([t[0] for t in mats_res.all() if t[0]])
        except Exception:
            pass

    material_text = "\n\n".join([t for t in texts if t]).strip()
    if not material_text:
        material_text = f"Course Title: {course.title}\nDescription: {course.description or 'Stock market trading fundamentals, technical analysis, and risk management.'}"

    try:
        mcqs = await generate_mcq_questions(
            material_text=material_text,
            question_count=assessment.question_count,
            difficulty=assessment.difficulty,
            course_title=course.title,
        )
    except AssessmentAIError as e:
        raise HTTPException(status_code=400, detail=str(e))

    existing_qs = await db.execute(select(Question).where(Question.assessment_id == assessment.id))
    for q in existing_qs.scalars().all():
        await db.delete(q)
    await db.commit()

    created_questions = []
    for idx, item in enumerate(mcqs):
        q = Question(
            assessment_id=assessment.id,
            order_index=idx,
            source="ai",
            text=item["text"].strip(),
        )
        db.add(q)
        await db.commit()
        await db.refresh(q)

        created_choices = []
        for c_idx, choice_data in enumerate(item["choices"]):
            c = Choice(
                question_id=q.id,
                text=choice_data["text"].strip(),
                is_correct=bool(choice_data.get("is_correct", False)),
                order_index=c_idx,
            )
            db.add(c)
            created_choices.append(c)

        await db.commit()
        created_questions.append(_question_out(q, created_choices))

    return {"success": True, "questions": created_questions}


@router.post("/courses/{course_id}/assessments/{assessment_id}/accept-questions")
async def accept_assessment_questions(
    course_id: str,
    assessment_id: str,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)
    assessment = await _get_own_assessment(db, course, assessment_id)
    return {"success": True, "message": "Questions accepted and saved successfully."}


@router.patch("/courses/{course_id}")
async def update_course(
    course_id: str,
    req: UpdateCourseRequest,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)
    _assert_editable(course)

    if req.title is not None:
        course.title = req.title.strip()
    if req.description is not None:
        course.description = req.description.strip() or None
    if course.status == "rejected":
        course.status = "pending"
        course.review_note = None

    await db.commit()
    await db.refresh(course)
    return _course_out(course)


@router.delete("/courses/{course_id}")
async def delete_course(
    course_id: str,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)
    await db.delete(course)
    await db.commit()
    return {"success": True}


# ── Lessons ───────────────────────────────────────────────────

@router.post("/courses/{course_id}/lessons")
async def add_lesson(
    course_id: str,
    req: LessonRequest,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)
    _assert_editable(course)

    lesson = Lesson(course_id=course.id, title=req.title.strip(), content=req.content, order_index=req.order_index)
    db.add(lesson)
    await db.commit()
    await db.refresh(lesson)
    return _lesson_out(lesson)


@router.patch("/courses/{course_id}/lessons/{lesson_id}")
async def update_lesson(
    course_id: str,
    lesson_id: str,
    req: LessonRequest,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)
    _assert_editable(course)
    lesson = await _get_own_lesson(db, course, lesson_id)

    lesson.title = req.title.strip()
    lesson.content = req.content
    lesson.order_index = req.order_index
    await db.commit()
    await db.refresh(lesson)
    return _lesson_out(lesson)


@router.post("/courses/{course_id}/lessons/{lesson_id}/material")
async def upload_lesson_material(
    course_id: str,
    lesson_id: str,
    file: UploadFile = File(...),
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)
    _assert_editable(course)
    lesson = await _get_own_lesson(db, course, lesson_id)

    file_type = ALLOWED_FILE_TYPES.get(file.content_type)
    if not file_type:
        raise HTTPException(status_code=400, detail="Unsupported file type. Upload a PDF, DOCX, PPTX, or Markdown file.")

    contents = await file.read()
    if len(contents) > MAX_FILE_SIZE_BYTES:
        raise HTTPException(status_code=400, detail="File too large. Maximum size is 15MB.")

    # Remove any previous material for this lesson
    old_path = _lesson_file_path(lesson)
    if old_path and os.path.exists(old_path):
        os.remove(old_path)

    filename = f"{lesson.id}_{uuid.uuid4().hex}.{file_type}"
    filepath = os.path.join(UPLOAD_DIR, filename)
    with open(filepath, "wb") as f:
        f.write(contents)

    lesson.file_url = f"/uploads/lesson-materials/{filename}"
    lesson.file_name = file.filename
    lesson.file_type = file_type
    lesson.extracted_text = text_extraction.extract_text(filepath, file_type)

    await db.commit()
    await db.refresh(lesson)
    return _lesson_out(lesson)


@router.delete("/courses/{course_id}/lessons/{lesson_id}/material")
async def delete_lesson_material(
    course_id: str,
    lesson_id: str,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)
    _assert_editable(course)
    lesson = await _get_own_lesson(db, course, lesson_id)

    old_path = _lesson_file_path(lesson)
    if old_path and os.path.exists(old_path):
        os.remove(old_path)
    lesson.file_url = None
    lesson.file_name = None
    lesson.file_type = None
    lesson.extracted_text = None

    await db.commit()
    await db.refresh(lesson)
    return _lesson_out(lesson)


@router.delete("/courses/{course_id}/lessons/{lesson_id}")
async def delete_lesson(
    course_id: str,
    lesson_id: str,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)
    _assert_editable(course)
    lesson = await _get_own_lesson(db, course, lesson_id)

    old_path = _lesson_file_path(lesson)
    if old_path and os.path.exists(old_path):
        os.remove(old_path)

    await db.delete(lesson)
    await db.commit()
    return {"success": True}


# ── Assessments ───────────────────────────────────────────────

@router.post("/courses/{course_id}/assessments")
async def add_assessment(
    course_id: str,
    req: AssessmentConfigRequest,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)
    _assert_editable(course)

    if req.difficulty not in ("easy", "medium", "hard"):
        raise HTTPException(status_code=400, detail="Difficulty must be easy, medium, or hard")

    assessment = Assessment(
        course_id=course.id,
        title=req.title.strip(),
        instructions=req.instructions,
        pass_score=req.pass_score,
        question_count=req.question_count,
        difficulty=req.difficulty,
        lesson_ids=req.lesson_ids or [],
    )
    db.add(assessment)
    await db.commit()
    await db.refresh(assessment)
    return _assessment_out(assessment)


@router.patch("/courses/{course_id}/assessments/{assessment_id}")
async def update_assessment_config(
    course_id: str,
    assessment_id: str,
    req: AssessmentConfigRequest,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)
    _assert_editable(course)
    assessment = await _get_own_assessment(db, course, assessment_id)

    if req.difficulty not in ("easy", "medium", "hard"):
        raise HTTPException(status_code=400, detail="Difficulty must be easy, medium, or hard")

    assessment.title = req.title.strip()
    assessment.instructions = req.instructions
    assessment.pass_score = req.pass_score
    assessment.question_count = req.question_count
    assessment.difficulty = req.difficulty
    if req.lesson_ids is not None:
        assessment.lesson_ids = req.lesson_ids
    await db.commit()
    await db.refresh(assessment)
    return _assessment_out(assessment)


@router.delete("/courses/{course_id}/assessments/{assessment_id}")
async def delete_assessment(
    course_id: str,
    assessment_id: str,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)
    _assert_editable(course)
    assessment = await _get_own_assessment(db, course, assessment_id)
    await db.delete(assessment)
    await db.commit()
    return {"success": True}


@router.get("/courses/{course_id}/assessments/{assessment_id}/questions")
async def list_questions(
    course_id: str,
    assessment_id: str,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)
    assessment = await _get_own_assessment(db, course, assessment_id)

    result = await db.execute(
        select(Question).where(Question.assessment_id == assessment.id).order_by(Question.order_index, Question.created_at)
    )
    questions = result.scalars().all()
    if not questions:
        return {"questions": []}

    question_ids = [q.id for q in questions]
    choices_result = await db.execute(select(Choice).where(Choice.question_id.in_(question_ids)))
    choices_by_question: dict = {}
    for c in choices_result.scalars().all():
        choices_by_question.setdefault(c.question_id, []).append(c)

    return {"questions": [_question_out(q, choices_by_question.get(q.id, [])) for q in questions]}


@router.post("/courses/{course_id}/assessments/{assessment_id}/questions")
async def add_manual_question(
    course_id: str,
    assessment_id: str,
    req: ManualQuestionRequest,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)
    _assert_editable(course)
    assessment = await _get_own_assessment(db, course, assessment_id)

    if not any(c.is_correct for c in req.choices):
        raise HTTPException(status_code=400, detail="Mark at least one choice as correct")

    existing_count_result = await db.execute(
        select(func.count(Question.id)).where(Question.assessment_id == assessment.id)
    )
    order_index = existing_count_result.scalar() or 0

    question = Question(assessment_id=assessment.id, text=req.text.strip(), order_index=order_index, source="manual")
    db.add(question)
    await db.flush()

    for idx, choice_in in enumerate(req.choices):
        db.add(Choice(question_id=question.id, text=choice_in.text.strip(), is_correct=choice_in.is_correct, order_index=idx))

    await db.commit()

    choices_result = await db.execute(select(Choice).where(Choice.question_id == question.id))
    return _question_out(question, choices_result.scalars().all())


@router.delete("/courses/{course_id}/assessments/{assessment_id}/questions/{question_id}")
async def delete_question(
    course_id: str,
    assessment_id: str,
    question_id: str,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)
    _assert_editable(course)
    assessment = await _get_own_assessment(db, course, assessment_id)

    question_uuid = _as_uuid(question_id)
    question = await db.get(Question, question_uuid) if question_uuid else None
    if not question or question.assessment_id != assessment.id:
        raise HTTPException(status_code=404, detail="Question not found")

    await db.delete(question)
    await db.commit()
    return {"success": True}


@router.post("/courses/{course_id}/assessments/{assessment_id}/generate")
async def generate_questions_with_ai(
    course_id: str,
    assessment_id: str,
    faculty: User = Depends(require_faculty),
    db: AsyncSession = Depends(get_db),
):
    course = await _get_own_course(db, faculty, course_id)
    _assert_editable(course)
    assessment = await _get_own_assessment(db, course, assessment_id)

    lessons_result = await db.execute(select(Lesson).where(Lesson.course_id == course.id))
    lessons = lessons_result.scalars().all()
    material_text = "\n\n".join(
        f"{l.title}\n{l.content or ''}\n{l.extracted_text or ''}".strip() for l in lessons
    ).strip()

    try:
        generated = await generate_mcq_questions(
            material_text=material_text,
            question_count=assessment.question_count,
            difficulty=assessment.difficulty,
            course_title=course.title,
        )
    except AssessmentAIError as exc:
        raise HTTPException(status_code=400, detail=str(exc))

    existing_count_result = await db.execute(
        select(func.count(Question.id)).where(Question.assessment_id == assessment.id)
    )
    order_offset = existing_count_result.scalar() or 0

    created_questions = []
    for i, q in enumerate(generated):
        question = Question(
            assessment_id=assessment.id,
            text=q["text"],
            order_index=order_offset + i,
            source="ai",
        )
        db.add(question)
        await db.flush()
        for idx, choice in enumerate(q["choices"]):
            db.add(Choice(question_id=question.id, text=choice["text"], is_correct=choice["is_correct"], order_index=idx))
        created_questions.append(question)

    await db.commit()

    question_ids = [q.id for q in created_questions]
    choices_result = await db.execute(select(Choice).where(Choice.question_id.in_(question_ids)))
    choices_by_question: dict = {}
    for c in choices_result.scalars().all():
        choices_by_question.setdefault(c.question_id, []).append(c)

    return {
        "questions": [_question_out(q, choices_by_question.get(q.id, [])) for q in created_questions],
        "generated_count": len(created_questions),
    }
