"""
AlphaSync Signal Generator — Smart strategy rule evaluation.

Each strategy uses MULTI-INDICATOR CONFIRMATION to avoid false signals.
A single indicator crossover is not enough — we require alignment from
at least 2-3 indicators before generating a BUY/SELL signal.

Strategies:
    SMA_CROSSOVER  — Golden/death cross + RSI + volume confirmation
    RSI            — Oversold/overbought + EMA trend filter + MACD confirm
    MACD           — Signal crossover + histogram momentum + RSI confirm
    BOLLINGER      — Band touch + RSI divergence + trend filter
    EMA_CROSSOVER  — Fast/slow EMA cross + MACD + volume surge
    VWAP_BOUNCE    — VWAP support/resistance + RSI + volume confirm
    SUPERTREND     — ATR trend channel pullback + momentum confirmation
    ATR_BREAKOUT   — Volatility breakout above/below ATR trigger levels
    STOCHASTIC_REVERSION — Mean reversion using stochastic K/D turns

Usage:
    from engines.signals import signal_generator, Signal
    signal = signal_generator.evaluate("SMA_CROSSOVER", indicators)
"""

import logging
from dataclasses import dataclass
from typing import Optional
from engines.indicators import IndicatorEngine

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """Trading signal generated by strategy evaluation."""

    action: str  # "BUY", "SELL", "HOLD"
    confidence: float = 0.0  # 0.0 to 1.0
    reason: str = ""
    indicator_values: dict = None

    def __post_init__(self):
        if self.indicator_values is None:
            self.indicator_values = {}


class SignalGenerator:
    """
    Smart signal generator with multi-indicator confirmation.

    Key principles:
    1. Never trade on a single indicator — require 2-3 confirmations
    2. Dynamic confidence based on how many confirmations align
    3. Volume must confirm the move (no low-volume signals)
    4. Trend filter prevents counter-trend entries
    """

    def evaluate(
        self,
        strategy_type: str,
        closes: list[float],
        highs: list[float] = None,
        lows: list[float] = None,
        volumes: list[int] = None,
        parameters: dict = None,
    ) -> Signal:
        params = parameters or {}

        match strategy_type:
            case "SMA_CROSSOVER":
                return self._sma_crossover(closes, highs, lows, volumes, params)
            case "RSI":
                return self._rsi_strategy(closes, highs, lows, volumes, params)
            case "MACD":
                return self._macd_strategy(closes, highs, lows, volumes, params)
            case "BOLLINGER":
                return self._bollinger_strategy(closes, highs, lows, volumes, params)
            case "EMA_CROSSOVER":
                return self._ema_crossover(closes, highs, lows, volumes, params)
            case "VWAP_BOUNCE":
                return self._vwap_bounce(closes, highs, lows, volumes, params)
            case "SUPERTREND":
                return self._supertrend_strategy(closes, highs, lows, volumes, params)
            case "ATR_BREAKOUT":
                return self._atr_breakout_strategy(closes, highs, lows, volumes, params)
            case "STOCHASTIC_REVERSION":
                return self._stochastic_reversion(closes, highs, lows, volumes, params)
            case "COMPOSITE":
                return self._composite_strategy(closes, highs, lows, volumes, params)
            case "MOMENTUM_BREAKOUT":
                return self._momentum_breakout(closes, highs, lows, volumes, params)
            case "MEAN_REVERSION_BB":
                return self._mean_reversion_bb(closes, highs, lows, volumes, params)
            case "TREND_STRENGTH_ADX":
                return self._trend_strength_adx(closes, highs, lows, volumes, params)
            case _:
                logger.warning(f"Unknown strategy type: {strategy_type}")
                return Signal(
                    action="HOLD", reason=f"Unknown strategy: {strategy_type}"
                )

    # ── Helper: compute common indicators ─────────────────────────────────────

    def _compute_common(self, closes, volumes=None):
        """Compute commonly used indicators for confirmation checks."""
        rsi_vals = IndicatorEngine.rsi(closes, 14)
        rsi = rsi_vals[-1] if rsi_vals else None

        macd_result = IndicatorEngine.macd(closes)
        macd_hist = None
        macd_prev_hist = None
        if macd_result:
            valid = [h for h in macd_result.histogram if h is not None]
            if len(valid) >= 2:
                macd_hist = valid[-1]
                macd_prev_hist = valid[-2]

        vol_ratio = None
        if volumes and len(volumes) >= 20:
            avg_vol = sum(volumes[-20:]) / 20
            if avg_vol > 0:
                vol_ratio = volumes[-1] / avg_vol

        ema_20 = IndicatorEngine.ema(closes, 20)
        ema_50 = IndicatorEngine.ema(closes, 50) if len(closes) >= 55 else None

        return {
            "rsi": rsi,
            "macd_hist": macd_hist,
            "macd_prev_hist": macd_prev_hist,
            "vol_ratio": round(vol_ratio, 2) if vol_ratio else None,
            "ema_20": ema_20[-1] if ema_20 and ema_20[-1] is not None else None,
            "ema_50": ema_50[-1] if ema_50 and ema_50[-1] is not None else None,
            "price": closes[-1],
        }

    def _compute_stochastic(
        self,
        highs: list[float],
        lows: list[float],
        closes: list[float],
        k_period: int,
        d_period: int,
    ) -> tuple[list[Optional[float]], list[Optional[float]]]:
        if not highs or not lows or len(highs) != len(lows) or len(lows) != len(closes):
            return [], []

        k_values: list[Optional[float]] = [None] * len(closes)
        for i in range(k_period - 1, len(closes)):
            window_high = max(highs[i - k_period + 1 : i + 1])
            window_low = min(lows[i - k_period + 1 : i + 1])
            if window_high == window_low:
                k_values[i] = 50.0
            else:
                k_values[i] = round(
                    (closes[i] - window_low) / (window_high - window_low) * 100,
                    2,
                )

        d_values: list[Optional[float]] = [None] * len(closes)
        valid_k: list[float] = []
        for i, k_val in enumerate(k_values):
            if k_val is None:
                continue
            valid_k.append(k_val)
            if len(valid_k) >= d_period:
                d_values[i] = round(sum(valid_k[-d_period:]) / d_period, 2)

        return k_values, d_values

    # ── SMA Crossover + Multi-Indicator ────────────────────────────────────────

    def _sma_crossover(self, closes, highs, lows, volumes, params) -> Signal:
        """
        SMA Crossover with RSI + volume confirmation.

        BUY:  Golden cross + RSI not overbought + volume above average
        SELL: Death cross + RSI not oversold + volume above average
        """
        short_period = params.get("short_period", 10)
        long_period = params.get("long_period", 20)

        if len(closes) < max(long_period + 2, 55):
            return Signal(action="HOLD", reason="Insufficient data for SMA crossover")

        short_sma = IndicatorEngine.sma(closes, short_period)
        long_sma = IndicatorEngine.sma(closes, long_period)

        curr_short, prev_short = short_sma[-1], short_sma[-2]
        curr_long, prev_long = long_sma[-1], long_sma[-2]

        if any(v is None for v in [curr_short, prev_short, curr_long, prev_long]):
            return Signal(action="HOLD", reason="Insufficient indicator data")

        common = self._compute_common(closes, volumes)

        indicator_vals = {
            "short_sma": curr_short,
            "long_sma": curr_long,
            "rsi": common["rsi"],
            "macd_hist": common["macd_hist"],
            "vol_ratio": common["vol_ratio"],
        }

        # Golden cross: short crosses above long
        if prev_short <= prev_long and curr_short > curr_long:
            confirmations = 0
            reasons = ["SMA golden cross detected"]

            # Confirmation 1: RSI is in bullish zone (not overbought)
            if common["rsi"] and 35 <= common["rsi"] <= 70:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} confirms (bullish zone)")
            elif common["rsi"] and common["rsi"] > 70:
                reasons.append(f"RSI {common['rsi']:.0f} overbought — weak signal")

            # Confirmation 2: MACD histogram positive or turning positive
            if common["macd_hist"] and common["macd_hist"] > 0:
                confirmations += 1
                reasons.append("MACD histogram positive")

            # Confirmation 3: Volume above average
            if common["vol_ratio"] and common["vol_ratio"] >= 1.0:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x avg confirms")

            confidence = min(0.5 + confirmations * 0.15, 0.95)

            if confirmations >= 1:
                return Signal(
                    action="BUY",
                    confidence=confidence,
                    reason=" | ".join(reasons),
                    indicator_values=indicator_vals,
                )
            return Signal(
                action="HOLD",
                reason="Golden cross but no confirmations",
                indicator_values=indicator_vals,
            )

        # Death cross: short crosses below long
        if prev_short >= prev_long and curr_short < curr_long:
            confirmations = 0
            reasons = ["SMA death cross detected"]

            if common["rsi"] and 30 <= common["rsi"] <= 65:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} confirms (bearish zone)")

            if common["macd_hist"] and common["macd_hist"] < 0:
                confirmations += 1
                reasons.append("MACD histogram negative")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.0:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x avg confirms")

            confidence = min(0.5 + confirmations * 0.15, 0.95)

            if confirmations >= 1:
                return Signal(
                    action="SELL",
                    confidence=confidence,
                    reason=" | ".join(reasons),
                    indicator_values=indicator_vals,
                )
            return Signal(
                action="HOLD",
                reason="Death cross but no confirmations",
                indicator_values=indicator_vals,
            )

        return Signal(
            action="HOLD", reason="No SMA crossover", indicator_values=indicator_vals
        )

    # ── RSI Strategy + Trend Filter ────────────────────────────────────────────

    def _rsi_strategy(self, closes, highs, lows, volumes, params) -> Signal:
        """
        RSI with EMA trend filter + MACD momentum confirmation.

        BUY:  RSI bounces from oversold + price above EMA-50 (uptrend) + MACD turning
        SELL: RSI enters overbought + price below EMA-50 (downtrend) + MACD turning
        """
        period = params.get("period", 14)
        oversold = params.get("oversold", 30)
        overbought = params.get("overbought", 70)

        if len(closes) < max(period + 3, 55):
            return Signal(action="HOLD", reason="Insufficient data for RSI")

        rsi_values = IndicatorEngine.rsi(closes, period)
        curr_rsi = rsi_values[-1]
        prev_rsi = rsi_values[-2] if len(rsi_values) >= 2 else None

        if curr_rsi is None or prev_rsi is None:
            return Signal(action="HOLD", reason="Insufficient RSI data")

        common = self._compute_common(closes, volumes)

        indicator_vals = {
            "rsi": curr_rsi,
            "prev_rsi": prev_rsi,
            "ema_20": common["ema_20"],
            "ema_50": common["ema_50"],
            "macd_hist": common["macd_hist"],
            "vol_ratio": common["vol_ratio"],
        }

        # BUY: RSI crosses up from oversold zone
        if prev_rsi <= oversold and curr_rsi > oversold:
            confirmations = 0
            reasons = [f"RSI bounced from oversold ({prev_rsi:.0f} → {curr_rsi:.0f})"]

            # Confirmation 1: Price above EMA-50 (in an uptrend)
            if common["ema_50"] and closes[-1] > common["ema_50"]:
                confirmations += 1
                reasons.append("Price above EMA-50 (uptrend)")
            elif common["ema_20"] and closes[-1] > common["ema_20"]:
                confirmations += 1
                reasons.append("Price above EMA-20 (short-term uptrend)")

            # Confirmation 2: MACD histogram turning positive
            if common["macd_hist"] is not None and common["macd_prev_hist"] is not None:
                if common["macd_hist"] > common["macd_prev_hist"]:
                    confirmations += 1
                    reasons.append("MACD momentum turning bullish")

            # Confirmation 3: Volume surge
            if common["vol_ratio"] and common["vol_ratio"] >= 1.2:
                confirmations += 1
                reasons.append(f"Volume surge {common['vol_ratio']:.1f}x")

            confidence = min(0.5 + confirmations * 0.15, 0.95)
            return Signal(
                action="BUY",
                confidence=confidence,
                reason=" | ".join(reasons),
                indicator_values=indicator_vals,
            )

        # SELL: RSI crosses into overbought zone
        if prev_rsi < overbought and curr_rsi >= overbought:
            confirmations = 0
            reasons = [f"RSI entered overbought ({prev_rsi:.0f} → {curr_rsi:.0f})"]

            if common["ema_50"] and closes[-1] < common["ema_50"]:
                confirmations += 1
                reasons.append("Price below EMA-50 (downtrend)")
            elif common["ema_20"] and closes[-1] < common["ema_20"]:
                confirmations += 1
                reasons.append("Price below EMA-20")

            if common["macd_hist"] is not None and common["macd_prev_hist"] is not None:
                if common["macd_hist"] < common["macd_prev_hist"]:
                    confirmations += 1
                    reasons.append("MACD momentum turning bearish")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.2:
                confirmations += 1
                reasons.append(f"Volume surge {common['vol_ratio']:.1f}x")

            confidence = min(0.5 + confirmations * 0.15, 0.95)
            return Signal(
                action="SELL",
                confidence=confidence,
                reason=" | ".join(reasons),
                indicator_values=indicator_vals,
            )

        # Also trigger on RSI staying deeply oversold/overbought (momentum extreme)
        if curr_rsi <= oversold - 5:
            if common["macd_hist"] is not None and common["macd_prev_hist"] is not None:
                if common["macd_hist"] > common["macd_prev_hist"]:  # momentum turning
                    return Signal(
                        action="BUY",
                        confidence=0.6,
                        reason=f"RSI deeply oversold ({curr_rsi:.0f}) + MACD turning up",
                        indicator_values=indicator_vals,
                    )

        if curr_rsi >= overbought + 5:
            if common["macd_hist"] is not None and common["macd_prev_hist"] is not None:
                if common["macd_hist"] < common["macd_prev_hist"]:
                    return Signal(
                        action="SELL",
                        confidence=0.6,
                        reason=f"RSI extremely overbought ({curr_rsi:.0f}) + MACD turning down",
                        indicator_values=indicator_vals,
                    )

        return Signal(
            action="HOLD",
            reason=f"RSI at {curr_rsi:.0f} — no signal",
            indicator_values=indicator_vals,
        )

    # ── MACD Strategy + Momentum + RSI ─────────────────────────────────────────

    def _macd_strategy(self, closes, highs, lows, volumes, params) -> Signal:
        """
        MACD signal crossover + histogram momentum + RSI confirmation.

        BUY:  MACD crosses above signal + histogram growing + RSI not overbought
        SELL: MACD crosses below signal + histogram growing + RSI not oversold
        """
        fast = params.get("fast_period", 12)
        slow = params.get("slow_period", 26)
        signal_period = params.get("signal_period", 9)

        macd_result = IndicatorEngine.macd(closes, fast, slow, signal_period)
        if macd_result is None:
            return Signal(action="HOLD", reason="Insufficient data for MACD")

        macd_line = macd_result.macd_line
        signal_line = macd_result.signal_line
        histogram = macd_result.histogram

        curr_macd, prev_macd = macd_line[-1], macd_line[-2]
        curr_signal, prev_signal = signal_line[-1], signal_line[-2]

        if any(v is None for v in [curr_macd, prev_macd, curr_signal, prev_signal]):
            return Signal(action="HOLD", reason="Insufficient MACD data")

        # Get histogram momentum (growing vs fading)
        valid_hist = [h for h in histogram if h is not None]
        hist_growing = False
        if len(valid_hist) >= 2:
            hist_growing = abs(valid_hist[-1]) > abs(valid_hist[-2])

        common = self._compute_common(closes, volumes)

        indicator_vals = {
            "macd": curr_macd,
            "signal": curr_signal,
            "histogram": valid_hist[-1] if valid_hist else None,
            "hist_growing": hist_growing,
            "rsi": common["rsi"],
            "vol_ratio": common["vol_ratio"],
        }

        # Bullish crossover
        if prev_macd <= prev_signal and curr_macd > curr_signal:
            confirmations = 0
            reasons = ["MACD bullish crossover"]

            # Confirmation 1: Histogram growing (momentum accelerating)
            if hist_growing and valid_hist[-1] > 0:
                confirmations += 1
                reasons.append("Histogram growing — strong momentum")

            # Confirmation 2: RSI in bullish zone
            if common["rsi"] and 30 <= common["rsi"] <= 65:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} confirms bullish")

            # Confirmation 3: Crossover above zero line (stronger signal)
            if curr_macd > 0:
                confirmations += 1
                reasons.append("Crossover above zero line — strong")

            # Confirmation 4: Volume
            if common["vol_ratio"] and common["vol_ratio"] >= 1.0:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x confirms")

            confidence = min(0.45 + confirmations * 0.12, 0.95)
            return Signal(
                action="BUY",
                confidence=confidence,
                reason=" | ".join(reasons),
                indicator_values=indicator_vals,
            )

        # Bearish crossover
        if prev_macd >= prev_signal and curr_macd < curr_signal:
            confirmations = 0
            reasons = ["MACD bearish crossover"]

            if hist_growing and valid_hist[-1] < 0:
                confirmations += 1
                reasons.append("Histogram growing negative — strong bearish")

            if common["rsi"] and 35 <= common["rsi"] <= 70:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} confirms bearish")

            if curr_macd < 0:
                confirmations += 1
                reasons.append("Crossover below zero line — strong")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.0:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x confirms")

            confidence = min(0.45 + confirmations * 0.12, 0.95)
            return Signal(
                action="SELL",
                confidence=confidence,
                reason=" | ".join(reasons),
                indicator_values=indicator_vals,
            )

        return Signal(
            action="HOLD", reason="No MACD crossover", indicator_values=indicator_vals
        )

    # ── Bollinger Bands + RSI + Trend ──────────────────────────────────────────

    def _bollinger_strategy(self, closes, highs, lows, volumes, params) -> Signal:
        """
        Bollinger Bands mean reversion with RSI + trend filter.

        BUY:  Price at lower band + RSI oversold + NOT in strong downtrend
        SELL: Price at upper band + RSI overbought + NOT in strong uptrend
        """
        period = params.get("period", 20)
        std_dev = params.get("std_dev", 2.0)

        if len(closes) < max(period, 55):
            return Signal(action="HOLD", reason="Insufficient data for Bollinger")

        bb_result = IndicatorEngine.bollinger_bands(closes, period, std_dev)
        if bb_result is None:
            return Signal(action="HOLD", reason="Insufficient Bollinger data")

        curr_price = closes[-1]
        curr_upper = bb_result.upper[-1]
        curr_lower = bb_result.lower[-1]
        curr_middle = bb_result.middle[-1]

        if any(v is None for v in [curr_upper, curr_lower, curr_middle]):
            return Signal(action="HOLD", reason="Insufficient Bollinger data")

        common = self._compute_common(closes, volumes)

        # Calculate %B (position within bands)
        band_width = curr_upper - curr_lower
        pct_b = (curr_price - curr_lower) / band_width if band_width > 0 else 0.5

        indicator_vals = {
            "price": curr_price,
            "upper": curr_upper,
            "middle": curr_middle,
            "lower": curr_lower,
            "pct_b": round(pct_b, 3),
            "rsi": common["rsi"],
            "ema_50": common["ema_50"],
            "vol_ratio": common["vol_ratio"],
        }

        # BUY: Price at or below lower band
        if curr_price <= curr_lower:
            confirmations = 0
            reasons = [f"Price at lower BB (₹{curr_price:.0f} ≤ ₹{curr_lower:.0f})"]

            # Confirmation 1: RSI confirms oversold
            if common["rsi"] and common["rsi"] <= 35:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} oversold")

            # Confirmation 2: NOT in a strong downtrend (don't catch falling knives)
            if common["ema_50"] and curr_price > common["ema_50"] * 0.97:
                confirmations += 1
                reasons.append("Not in strong downtrend (price near EMA-50)")
            elif common["ema_20"] and curr_price > common["ema_20"] * 0.98:
                confirmations += 1
                reasons.append("Price near EMA-20 — potential bounce")

            # Confirmation 3: Volume spike (capitulation / accumulation)
            if common["vol_ratio"] and common["vol_ratio"] >= 1.5:
                confirmations += 1
                reasons.append(
                    f"Volume spike {common['vol_ratio']:.1f}x — potential capitulation"
                )

            # Confirmation 4: MACD turning up
            if common["macd_hist"] is not None and common["macd_prev_hist"] is not None:
                if common["macd_hist"] > common["macd_prev_hist"]:
                    confirmations += 1
                    reasons.append("MACD momentum turning up")

            if confirmations >= 1:
                confidence = min(0.45 + confirmations * 0.12, 0.90)
                return Signal(
                    action="BUY",
                    confidence=confidence,
                    reason=" | ".join(reasons),
                    indicator_values=indicator_vals,
                )
            return Signal(
                action="HOLD",
                reason="Lower BB touch but no confirmations",
                indicator_values=indicator_vals,
            )

        # SELL: Price at or above upper band
        if curr_price >= curr_upper:
            confirmations = 0
            reasons = [f"Price at upper BB (₹{curr_price:.0f} ≥ ₹{curr_upper:.0f})"]

            if common["rsi"] and common["rsi"] >= 65:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} overbought")

            if common["ema_50"] and curr_price < common["ema_50"] * 1.03:
                confirmations += 1
                reasons.append("Not in strong uptrend")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.5:
                confirmations += 1
                reasons.append(
                    f"Volume spike {common['vol_ratio']:.1f}x — distribution"
                )

            if common["macd_hist"] is not None and common["macd_prev_hist"] is not None:
                if common["macd_hist"] < common["macd_prev_hist"]:
                    confirmations += 1
                    reasons.append("MACD momentum fading")

            if confirmations >= 1:
                confidence = min(0.45 + confirmations * 0.12, 0.90)
                return Signal(
                    action="SELL",
                    confidence=confidence,
                    reason=" | ".join(reasons),
                    indicator_values=indicator_vals,
                )
            return Signal(
                action="HOLD",
                reason="Upper BB touch but no confirmations",
                indicator_values=indicator_vals,
            )

        return Signal(
            action="HOLD",
            reason=f"Price within bands (%B: {pct_b:.1%})",
            indicator_values=indicator_vals,
        )

    # ── EMA Crossover (NEW) ────────────────────────────────────────────────────

    def _ema_crossover(self, closes, highs, lows, volumes, params) -> Signal:
        """
        EMA Crossover — faster than SMA, better for trending markets.

        BUY:  Fast EMA crosses above slow EMA + MACD positive + volume surge
        SELL: Fast EMA crosses below slow EMA + MACD negative + volume surge
        """
        fast_period = params.get("fast_period", 9)
        slow_period = params.get("slow_period", 21)

        if len(closes) < max(slow_period + 2, 55):
            return Signal(action="HOLD", reason="Insufficient data for EMA crossover")

        fast_ema = IndicatorEngine.ema(closes, fast_period)
        slow_ema = IndicatorEngine.ema(closes, slow_period)

        curr_fast, prev_fast = fast_ema[-1], fast_ema[-2]
        curr_slow, prev_slow = slow_ema[-1], slow_ema[-2]

        if any(v is None for v in [curr_fast, prev_fast, curr_slow, prev_slow]):
            return Signal(action="HOLD", reason="Insufficient EMA data")

        common = self._compute_common(closes, volumes)

        indicator_vals = {
            "fast_ema": curr_fast,
            "slow_ema": curr_slow,
            "spread_pct": (
                round((curr_fast - curr_slow) / curr_slow * 100, 3) if curr_slow else 0
            ),
            "rsi": common["rsi"],
            "macd_hist": common["macd_hist"],
            "vol_ratio": common["vol_ratio"],
        }

        # Bullish EMA crossover
        if prev_fast <= prev_slow and curr_fast > curr_slow:
            confirmations = 0
            reasons = [f"EMA({fast_period}) crossed above EMA({slow_period})"]

            if common["rsi"] and 40 <= common["rsi"] <= 70:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} bullish")

            if common["macd_hist"] and common["macd_hist"] > 0:
                confirmations += 1
                reasons.append("MACD positive")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.1:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x confirms")

            confidence = min(0.5 + confirmations * 0.15, 0.95)
            if confirmations >= 1:
                return Signal(
                    action="BUY",
                    confidence=confidence,
                    reason=" | ".join(reasons),
                    indicator_values=indicator_vals,
                )

        # Bearish EMA crossover
        if prev_fast >= prev_slow and curr_fast < curr_slow:
            confirmations = 0
            reasons = [f"EMA({fast_period}) crossed below EMA({slow_period})"]

            if common["rsi"] and 30 <= common["rsi"] <= 60:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} bearish")

            if common["macd_hist"] and common["macd_hist"] < 0:
                confirmations += 1
                reasons.append("MACD negative")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.1:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x confirms")

            confidence = min(0.5 + confirmations * 0.15, 0.95)
            if confirmations >= 1:
                return Signal(
                    action="SELL",
                    confidence=confidence,
                    reason=" | ".join(reasons),
                    indicator_values=indicator_vals,
                )

        return Signal(
            action="HOLD", reason="No EMA crossover", indicator_values=indicator_vals
        )

    # ── VWAP Bounce (NEW) ──────────────────────────────────────────────────────

    def _vwap_bounce(self, closes, highs, lows, volumes, params) -> Signal:
        """
        VWAP Support/Resistance bounce — best for intraday.

        BUY:  Price bounces off VWAP support + RSI confirms + volume confirms
        SELL: Price rejected at VWAP resistance + RSI confirms + volume confirms
        """
        if not highs or not lows or not volumes:
            return Signal(action="HOLD", reason="Need OHLCV data for VWAP")

        if len(closes) < 30:
            return Signal(action="HOLD", reason="Insufficient data for VWAP")

        vwap_vals = IndicatorEngine.vwap(highs, lows, closes, volumes)
        if not vwap_vals or vwap_vals[-1] is None:
            return Signal(action="HOLD", reason="VWAP calculation failed")

        curr_vwap = vwap_vals[-1]
        curr_price = closes[-1]
        prev_price = closes[-2]

        # Price distance from VWAP as percentage
        vwap_dist_pct = (curr_price - curr_vwap) / curr_vwap * 100 if curr_vwap else 0

        common = self._compute_common(closes, volumes)

        indicator_vals = {
            "price": curr_price,
            "vwap": curr_vwap,
            "vwap_dist_pct": round(vwap_dist_pct, 3),
            "rsi": common["rsi"],
            "vol_ratio": common["vol_ratio"],
        }

        # BUY: Price bounces UP from near/below VWAP
        if prev_price <= curr_vwap * 1.002 and curr_price > curr_vwap:
            confirmations = 0
            reasons = [f"Price bounced above VWAP (₹{curr_vwap:.0f})"]

            if common["rsi"] and common["rsi"] <= 55:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} not overbought")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.0:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x confirms")

            if common["macd_hist"] and common["macd_hist"] > 0:
                confirmations += 1
                reasons.append("MACD positive")

            if confirmations >= 2:
                confidence = min(0.5 + confirmations * 0.12, 0.90)
                return Signal(
                    action="BUY",
                    confidence=confidence,
                    reason=" | ".join(reasons),
                    indicator_values=indicator_vals,
                )

        # SELL: Price rejected DOWN from near/above VWAP
        if prev_price >= curr_vwap * 0.998 and curr_price < curr_vwap:
            confirmations = 0
            reasons = [f"Price rejected below VWAP (₹{curr_vwap:.0f})"]

            if common["rsi"] and common["rsi"] >= 45:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} not oversold")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.0:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x confirms")

            if common["macd_hist"] and common["macd_hist"] < 0:
                confirmations += 1
                reasons.append("MACD negative")

            if confirmations >= 2:
                confidence = min(0.5 + confirmations * 0.12, 0.90)
                return Signal(
                    action="SELL",
                    confidence=confidence,
                    reason=" | ".join(reasons),
                    indicator_values=indicator_vals,
                )

        return Signal(
            action="HOLD",
            reason=f"Price {vwap_dist_pct:+.1f}% from VWAP — no signal",
            indicator_values=indicator_vals,
        )

    # ── Supertrend Pullback (NEW) ────────────────────────────────────────────

    def _supertrend_strategy(self, closes, highs, lows, volumes, params) -> Signal:
        """
        ATR channel pullback strategy inspired by Supertrend behavior.

        BUY: price reclaims lower ATR channel in uptrend + momentum confirmation
        SELL: price rejects upper ATR channel in downtrend + momentum confirmation
        """
        if not highs or not lows or len(highs) != len(lows) or len(lows) != len(closes):
            return Signal(action="HOLD", reason="Need OHLC data for Supertrend")

        atr_period = int(params.get("atr_period", 10))
        multiplier = float(params.get("multiplier", 3.0))

        if len(closes) < max(atr_period + 3, 55):
            return Signal(action="HOLD", reason="Insufficient data for Supertrend")

        atr_vals = IndicatorEngine.atr(highs, lows, closes, atr_period)
        curr_atr = atr_vals[-1] if atr_vals else None
        prev_atr = atr_vals[-2] if atr_vals and len(atr_vals) >= 2 else None
        if curr_atr is None or prev_atr is None:
            return Signal(action="HOLD", reason="Insufficient ATR data")

        curr_mid = (highs[-1] + lows[-1]) / 2.0
        prev_mid = (highs[-2] + lows[-2]) / 2.0
        curr_upper = curr_mid + multiplier * curr_atr
        curr_lower = curr_mid - multiplier * curr_atr
        prev_upper = prev_mid + multiplier * prev_atr
        prev_lower = prev_mid - multiplier * prev_atr

        curr_price = closes[-1]
        prev_price = closes[-2]
        common = self._compute_common(closes, volumes)

        indicator_vals = {
            "price": curr_price,
            "atr": curr_atr,
            "upper": round(curr_upper, 4),
            "lower": round(curr_lower, 4),
            "ema_20": common["ema_20"],
            "ema_50": common["ema_50"],
            "rsi": common["rsi"],
            "macd_hist": common["macd_hist"],
            "vol_ratio": common["vol_ratio"],
        }

        uptrend = (
            common["ema_20"] is not None
            and common["ema_50"] is not None
            and curr_price >= common["ema_20"] >= common["ema_50"]
        )
        downtrend = (
            common["ema_20"] is not None
            and common["ema_50"] is not None
            and curr_price <= common["ema_20"] <= common["ema_50"]
        )

        # Bullish reclaim from ATR lower channel
        if prev_price <= prev_lower and curr_price > curr_lower:
            confirmations = 0
            reasons = ["Price reclaimed ATR lower channel"]

            if uptrend:
                confirmations += 1
                reasons.append("EMA trend is up")
            if common["rsi"] and 35 <= common["rsi"] <= 70:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} supports buy")
            if common["macd_hist"] and common["macd_hist"] > 0:
                confirmations += 1
                reasons.append("MACD histogram positive")
            if common["vol_ratio"] and common["vol_ratio"] >= 1.1:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x confirms")

            if confirmations >= 2:
                confidence = min(0.5 + confirmations * 0.1, 0.92)
                return Signal(
                    action="BUY",
                    confidence=confidence,
                    reason=" | ".join(reasons),
                    indicator_values=indicator_vals,
                )

        # Bearish rejection from ATR upper channel
        if prev_price >= prev_upper and curr_price < curr_upper:
            confirmations = 0
            reasons = ["Price rejected from ATR upper channel"]

            if downtrend:
                confirmations += 1
                reasons.append("EMA trend is down")
            if common["rsi"] and 30 <= common["rsi"] <= 65:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} supports sell")
            if common["macd_hist"] and common["macd_hist"] < 0:
                confirmations += 1
                reasons.append("MACD histogram negative")
            if common["vol_ratio"] and common["vol_ratio"] >= 1.1:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x confirms")

            if confirmations >= 2:
                confidence = min(0.5 + confirmations * 0.1, 0.92)
                return Signal(
                    action="SELL",
                    confidence=confidence,
                    reason=" | ".join(reasons),
                    indicator_values=indicator_vals,
                )

        return Signal(
            action="HOLD",
            reason="No Supertrend pullback setup",
            indicator_values=indicator_vals,
        )

    # ── ATR Breakout (NEW) ──────────────────────────────────────────────────

    def _atr_breakout_strategy(self, closes, highs, lows, volumes, params) -> Signal:
        """
        Volatility breakout with ATR expansion filters.

        BUY: close breaks above recent range by ATR threshold
        SELL: close breaks below recent range by ATR threshold
        """
        if not highs or not lows or len(highs) != len(lows) or len(lows) != len(closes):
            return Signal(action="HOLD", reason="Need OHLC data for ATR breakout")

        period = int(params.get("period", 14))
        breakout_multiplier = float(params.get("breakout_multiplier", 1.2))

        if len(closes) < period + 5:
            return Signal(action="HOLD", reason="Insufficient data for ATR breakout")

        atr_vals = IndicatorEngine.atr(highs, lows, closes, period)
        curr_atr = atr_vals[-1] if atr_vals else None
        if curr_atr is None:
            return Signal(action="HOLD", reason="Insufficient ATR for breakout")

        lookback_high = max(highs[-period - 1 : -1])
        lookback_low = min(lows[-period - 1 : -1])
        upper_trigger = lookback_high + breakout_multiplier * curr_atr
        lower_trigger = lookback_low - breakout_multiplier * curr_atr

        curr_price = closes[-1]
        prev_price = closes[-2]
        common = self._compute_common(closes, volumes)

        indicator_vals = {
            "price": curr_price,
            "atr": curr_atr,
            "upper_trigger": round(upper_trigger, 4),
            "lower_trigger": round(lower_trigger, 4),
            "range_high": lookback_high,
            "range_low": lookback_low,
            "vol_ratio": common["vol_ratio"],
            "macd_hist": common["macd_hist"],
            "rsi": common["rsi"],
        }

        if prev_price <= upper_trigger and curr_price > upper_trigger:
            confirmations = 0
            reasons = ["ATR upside breakout"]

            if common["vol_ratio"] and common["vol_ratio"] >= 1.2:
                confirmations += 1
                reasons.append(f"Volume expansion {common['vol_ratio']:.1f}x")
            if common["macd_hist"] and common["macd_hist"] > 0:
                confirmations += 1
                reasons.append("MACD confirms momentum")
            if common["rsi"] and common["rsi"] <= 75:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} not extreme")

            if confirmations >= 2:
                confidence = min(0.55 + confirmations * 0.1, 0.92)
                return Signal(
                    action="BUY",
                    confidence=confidence,
                    reason=" | ".join(reasons),
                    indicator_values=indicator_vals,
                )

        if prev_price >= lower_trigger and curr_price < lower_trigger:
            confirmations = 0
            reasons = ["ATR downside breakout"]

            if common["vol_ratio"] and common["vol_ratio"] >= 1.2:
                confirmations += 1
                reasons.append(f"Volume expansion {common['vol_ratio']:.1f}x")
            if common["macd_hist"] and common["macd_hist"] < 0:
                confirmations += 1
                reasons.append("MACD confirms downside")
            if common["rsi"] and common["rsi"] >= 25:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} not deeply oversold")

            if confirmations >= 2:
                confidence = min(0.55 + confirmations * 0.1, 0.92)
                return Signal(
                    action="SELL",
                    confidence=confidence,
                    reason=" | ".join(reasons),
                    indicator_values=indicator_vals,
                )

        return Signal(
            action="HOLD", reason="No ATR breakout", indicator_values=indicator_vals
        )

    # ── Stochastic Reversion (NEW) ───────────────────────────────────────────

    def _stochastic_reversion(self, closes, highs, lows, volumes, params) -> Signal:
        """
        Mean-reversion entries based on stochastic K/D turns.

        BUY: K exits oversold and crosses above D
        SELL: K exits overbought and crosses below D
        """
        if not highs or not lows or len(highs) != len(lows) or len(lows) != len(closes):
            return Signal(action="HOLD", reason="Need OHLC data for stochastic")

        k_period = int(params.get("k_period", 14))
        d_period = int(params.get("d_period", 3))
        oversold = float(params.get("oversold", 20))
        overbought = float(params.get("overbought", 80))

        min_required = k_period + d_period + 2
        if len(closes) < min_required:
            return Signal(action="HOLD", reason="Insufficient data for stochastic")

        k_vals, d_vals = self._compute_stochastic(
            highs, lows, closes, k_period, d_period
        )
        if not k_vals or not d_vals:
            return Signal(action="HOLD", reason="Stochastic calculation failed")

        curr_k, prev_k = k_vals[-1], k_vals[-2]
        curr_d, prev_d = d_vals[-1], d_vals[-2]
        if any(v is None for v in [curr_k, prev_k, curr_d, prev_d]):
            return Signal(action="HOLD", reason="Insufficient stochastic values")

        common = self._compute_common(closes, volumes)
        indicator_vals = {
            "k": curr_k,
            "d": curr_d,
            "oversold": oversold,
            "overbought": overbought,
            "rsi": common["rsi"],
            "macd_hist": common["macd_hist"],
            "vol_ratio": common["vol_ratio"],
            "ema_20": common["ema_20"],
        }

        # BUY setup: K exits oversold and crosses up D
        if (
            prev_k <= oversold
            and curr_k > oversold
            and prev_k <= prev_d
            and curr_k > curr_d
        ):
            confirmations = 0
            reasons = [
                f"Stochastic K recovered from oversold ({prev_k:.0f} to {curr_k:.0f})"
            ]

            if common["rsi"] and common["rsi"] <= 55:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} supports reversion")
            if (
                common["macd_hist"] is not None
                and common["macd_prev_hist"] is not None
                and common["macd_hist"] > common["macd_prev_hist"]
            ):
                confirmations += 1
                reasons.append("MACD momentum improving")
            if common["vol_ratio"] and common["vol_ratio"] >= 1.0:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x confirms")

            confidence = min(0.5 + confirmations * 0.12, 0.9)
            return Signal(
                action="BUY",
                confidence=confidence,
                reason=" | ".join(reasons),
                indicator_values=indicator_vals,
            )

        # SELL setup: K exits overbought and crosses down D
        if (
            prev_k >= overbought
            and curr_k < overbought
            and prev_k >= prev_d
            and curr_k < curr_d
        ):
            confirmations = 0
            reasons = [
                f"Stochastic K dropped from overbought ({prev_k:.0f} to {curr_k:.0f})"
            ]

            if common["rsi"] and common["rsi"] >= 45:
                confirmations += 1
                reasons.append(f"RSI {common['rsi']:.0f} supports pullback")
            if (
                common["macd_hist"] is not None
                and common["macd_prev_hist"] is not None
                and common["macd_hist"] < common["macd_prev_hist"]
            ):
                confirmations += 1
                reasons.append("MACD momentum weakening")
            if common["vol_ratio"] and common["vol_ratio"] >= 1.0:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x confirms")

            confidence = min(0.5 + confirmations * 0.12, 0.9)
            return Signal(
                action="SELL",
                confidence=confidence,
                reason=" | ".join(reasons),
                indicator_values=indicator_vals,
            )

        return Signal(
            action="HOLD",
            reason="No stochastic reversion setup",
            indicator_values=indicator_vals,
        )

    # ── Multi-Strategy Composite Builder Evaluation ─────────────────────────

    def _composite_strategy(self, closes, highs, lows, volumes, params) -> Signal:
        """
        Combines multiple strategy rules using logical ALL (AND) or ANY (OR) combination modes.
        """
        rules = params.get("rules", [])
        combination_mode = str(params.get("combination_mode", "ALL")).strip().upper()

        if not rules:
            return Signal(action="HOLD", reason="No composite rules defined")

        sub_signals: list[tuple[str, Signal]] = []
        all_indicators: dict = {}

        for rule in rules:
            if not isinstance(rule, dict):
                continue
            stype = rule.get("type")
            sparams = rule.get("params", {})
            if not isinstance(sparams, dict):
                sparams = {}
            if stype and stype != "COMPOSITE":
                sig = self.evaluate(stype, closes, highs, lows, volumes, sparams)
                sub_signals.append((stype, sig))
                if sig.indicator_values:
                    all_indicators[stype] = sig.indicator_values

        if not sub_signals:
            return Signal(action="HOLD", reason="No valid composite sub-rules evaluated")

        if combination_mode == "ANY":
            # ANY (OR) mode: Trigger if any rule signals BUY or SELL
            active_buys = [s for t, s in sub_signals if s.action == "BUY"]
            active_sells = [s for t, s in sub_signals if s.action == "SELL"]

            if active_buys and not active_sells:
                reasons = [f"[{t}] {s.reason}" for t, s in sub_signals if s.action == "BUY"]
                max_conf = max(s.confidence for s in active_buys)
                return Signal(
                    action="BUY",
                    confidence=min(0.95, max_conf + (len(active_buys) - 1) * 0.05),
                    reason=f"Composite (ANY Mode - {len(active_buys)} triggered): " + " | ".join(reasons),
                    indicator_values=all_indicators,
                )
            if active_sells and not active_buys:
                reasons = [f"[{t}] {s.reason}" for t, s in sub_signals if s.action == "SELL"]
                max_conf = max(s.confidence for s in active_sells)
                return Signal(
                    action="SELL",
                    confidence=min(0.95, max_conf + (len(active_sells) - 1) * 0.05),
                    reason=f"Composite (ANY Mode - {len(active_sells)} triggered): " + " | ".join(reasons),
                    indicator_values=all_indicators,
                )
            return Signal(
                action="HOLD",
                reason=f"Composite ANY Mode: {len(active_buys)} Buy and {len(active_sells)} Sell rules triggered (Conflict)",
                indicator_values=all_indicators,
            )

        else:
            # ALL (AND) mode: All rules must unanimously agree on BUY or SELL
            actions = {s.action for t, s in sub_signals}
            if len(actions) == 1 and "BUY" in actions:
                reasons = [f"[{t}] {s.reason}" for t, s in sub_signals]
                avg_conf = sum(s.confidence for t, s in sub_signals) / len(sub_signals)
                return Signal(
                    action="BUY",
                    confidence=min(0.95, avg_conf + 0.1),
                    reason=f"Composite (ALL Unanimous BUY - {len(sub_signals)} rules): " + " | ".join(reasons),
                    indicator_values=all_indicators,
                )
            if len(actions) == 1 and "SELL" in actions:
                reasons = [f"[{t}] {s.reason}" for t, s in sub_signals]
                avg_conf = sum(s.confidence for t, s in sub_signals) / len(sub_signals)
                return Signal(
                    action="SELL",
                    confidence=min(0.95, avg_conf + 0.1),
                    reason=f"Composite (ALL Unanimous SELL - {len(sub_signals)} rules): " + " | ".join(reasons),
                    indicator_values=all_indicators,
                )

            aligned_count = max(
                sum(1 for _, s in sub_signals if s.action == "BUY"),
                sum(1 for _, s in sub_signals if s.action == "SELL"),
            )
            return Signal(
                action="HOLD",
                reason=f"Composite ALL Mode: Waiting for all {len(rules)} rules to align ({aligned_count}/{len(rules)} currently aligned)",
                indicator_values=all_indicators,
            )

    # ── Momentum Breakout ─────────────────────────────────────────────────────

    def _momentum_breakout(self, closes, highs, lows, volumes, params) -> Signal:
        """
        Momentum Breakout — Price breaks above N-bar high (BUY) or below N-bar low (SELL)
        with volume surge + RSI momentum confirmation.

        BUY:  Close > rolling_high[N-1] (prev bar's high) + volume surge + RSI > 50
        SELL: Close < rolling_low[N-1] (prev bar's low)  + volume surge + RSI < 50
        """
        lookback = int(params.get("lookback_period", 20))
        vol_mult = float(params.get("volume_multiplier", 1.5))

        if len(closes) < lookback + 5:
            return Signal(action="HOLD", reason="Insufficient data for Momentum Breakout")

        roll_high = IndicatorEngine.rolling_high(highs, lookback)
        roll_low = IndicatorEngine.rolling_low(lows, lookback)

        # Use the bar BEFORE current (index -2) as the breakout reference
        prev_high = roll_high[-2] if len(roll_high) >= 2 else None
        prev_low  = roll_low[-2]  if len(roll_low) >= 2 else None
        curr_close = closes[-1]
        prev_close = closes[-2] if len(closes) >= 2 else closes[-1]

        if prev_high is None or prev_low is None:
            return Signal(action="HOLD", reason="Insufficient breakout reference data")

        common = self._compute_common(closes, volumes)
        rsi = common["rsi"]

        # Volume surge check
        vol_surge = common["vol_ratio"] and common["vol_ratio"] >= vol_mult

        indicator_vals = {
            "close": curr_close,
            "breakout_high": prev_high,
            "breakout_low": prev_low,
            "rsi": rsi,
            "vol_ratio": common["vol_ratio"],
            "macd_hist": common["macd_hist"],
        }

        # BUY: Close breaks above N-bar high
        if curr_close > prev_high and prev_close <= prev_high:
            confirmations = 0
            reasons = [f"Price broke above {lookback}-bar high ₹{prev_high:.2f}"]

            if rsi and rsi > 50:
                confirmations += 1
                reasons.append(f"RSI {rsi:.0f} in bullish zone")

            if vol_surge:
                confirmations += 1
                reasons.append(f"Volume surge {common['vol_ratio']:.1f}x avg")

            if common["macd_hist"] and common["macd_hist"] > 0:
                confirmations += 1
                reasons.append("MACD positive momentum")

            confidence = min(0.55 + confirmations * 0.15, 0.95)
            if confirmations >= 1:
                return Signal(
                    action="BUY",
                    confidence=confidence,
                    reason=" | ".join(reasons),
                    indicator_values=indicator_vals,
                )

        # SELL: Close breaks below N-bar low
        if curr_close < prev_low and prev_close >= prev_low:
            confirmations = 0
            reasons = [f"Price broke below {lookback}-bar low ₹{prev_low:.2f}"]

            if rsi and rsi < 50:
                confirmations += 1
                reasons.append(f"RSI {rsi:.0f} in bearish zone")

            if vol_surge:
                confirmations += 1
                reasons.append(f"Volume surge {common['vol_ratio']:.1f}x avg")

            if common["macd_hist"] and common["macd_hist"] < 0:
                confirmations += 1
                reasons.append("MACD negative momentum")

            confidence = min(0.55 + confirmations * 0.15, 0.95)
            if confirmations >= 1:
                return Signal(
                    action="SELL",
                    confidence=confidence,
                    reason=" | ".join(reasons),
                    indicator_values=indicator_vals,
                )

        return Signal(
            action="HOLD",
            reason=f"No breakout: range ₹{prev_low:.2f}–₹{prev_high:.2f} | close ₹{curr_close:.2f}",
            indicator_values=indicator_vals,
        )

    # ── Mean Reversion BB with ADX Ranging Filter ─────────────────────────────

    def _mean_reversion_bb(self, closes, highs, lows, volumes, params) -> Signal:
        """
        Mean Reversion Bollinger Bands with ADX ranging filter.

        Only fires in LOW-TREND (ADX < 25) — pure ranging markets.
        BUY:  Price touches/crosses below lower BB + RSI oversold + ADX < 25
        SELL: Price touches/crosses above upper BB + RSI overbought + ADX < 25
        """
        period = int(params.get("period", 20))
        std_dev = float(params.get("std_dev", 2.0))
        adx_threshold = float(params.get("adx_threshold", 25.0))

        if len(closes) < period + 15:
            return Signal(action="HOLD", reason="Insufficient data for Mean Reversion BB")

        bb = IndicatorEngine.bollinger_bands(closes, period, std_dev)
        if not bb:
            return Signal(action="HOLD", reason="Bollinger Bands failed")

        upper = bb.upper[-1]
        lower = bb.lower[-1]
        middle = bb.middle[-1]

        if any(v is None for v in [upper, lower, middle]):
            return Signal(action="HOLD", reason="Bollinger data incomplete")

        adx_result = IndicatorEngine.adx(highs, lows, closes, 14)
        adx_val = adx_result["adx"][-1]
        plus_di = adx_result["plus_di"][-1]
        minus_di = adx_result["minus_di"][-1]

        common = self._compute_common(closes, volumes)
        rsi = common["rsi"]
        curr_price = closes[-1]
        prev_price = closes[-2] if len(closes) >= 2 else closes[-1]

        band_width = (upper - lower) / middle * 100 if middle > 0 else 0

        indicator_vals = {
            "price": curr_price,
            "bb_upper": upper,
            "bb_lower": lower,
            "bb_middle": middle,
            "band_width_pct": round(band_width, 2),
            "adx": adx_val,
            "plus_di": plus_di,
            "minus_di": minus_di,
            "rsi": rsi,
            "vol_ratio": common["vol_ratio"],
        }

        # ADX filter: only trade in ranging markets
        is_ranging = adx_val is None or adx_val < adx_threshold

        # BUY: Price enters/exits lower band
        if curr_price <= lower and prev_price > lower:
            reasons = [f"Price touched lower BB ₹{lower:.2f} (band -{std_dev:.1f}σ)"]
            confirmations = 0

            if is_ranging:
                confirmations += 1
                adx_str = f"{adx_val:.0f}" if adx_val is not None else "N/A"
                reasons.append(f"ADX {adx_str} — ranging market confirmed")
            else:
                return Signal(
                    action="HOLD",
                    reason=f"BB lower touch but ADX {adx_val:.0f} > {adx_threshold} — trending, avoid mean reversion",
                    indicator_values=indicator_vals,
                )

            if rsi and rsi < 40:
                confirmations += 1
                reasons.append(f"RSI {rsi:.0f} oversold")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.2:
                confirmations += 1
                reasons.append(f"Volume spike {common['vol_ratio']:.1f}x")

            return Signal(
                action="BUY",
                confidence=min(0.5 + confirmations * 0.15, 0.90),
                reason=" | ".join(reasons),
                indicator_values=indicator_vals,
            )

        # SELL: Price enters/exits upper band
        if curr_price >= upper and prev_price < upper:
            reasons = [f"Price touched upper BB ₹{upper:.2f} (band +{std_dev:.1f}σ)"]
            confirmations = 0

            if is_ranging:
                confirmations += 1
                adx_str = f"{adx_val:.0f}" if adx_val is not None else "N/A"
                reasons.append(f"ADX {adx_str} — ranging market")
            else:
                return Signal(
                    action="HOLD",
                    reason=f"BB upper touch but ADX {adx_val:.0f} > {adx_threshold} — avoid mean reversion in trend",
                    indicator_values=indicator_vals,
                )

            if rsi and rsi > 60:
                confirmations += 1
                reasons.append(f"RSI {rsi:.0f} overbought")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.2:
                confirmations += 1
                reasons.append(f"Volume spike {common['vol_ratio']:.1f}x")

            return Signal(
                action="SELL",
                confidence=min(0.5 + confirmations * 0.15, 0.90),
                reason=" | ".join(reasons),
                indicator_values=indicator_vals,
            )

        return Signal(
            action="HOLD",
            reason=f"Price ₹{curr_price:.2f} within BB [₹{lower:.2f}–₹{upper:.2f}]",
            indicator_values=indicator_vals,
        )

    # ── ADX Trend Strength ─────────────────────────────────────────────────────

    def _trend_strength_adx(self, closes, highs, lows, volumes, params) -> Signal:
        """
        ADX Trend Strength — Trades ONLY when ADX confirms strong trend.

        BUY:  ADX >= threshold + +DI > -DI + EMA confirms uptrend + MACD bullish
        SELL: ADX >= threshold + -DI > +DI + EMA confirms downtrend + MACD bearish

        High-quality signals — fires less frequently but with very high confidence.
        """
        adx_threshold = float(params.get("adx_threshold", 25.0))
        di_gap = float(params.get("di_gap", 5.0))  # min DI separation
        ema_fast = int(params.get("fast_ema", 9))
        ema_slow = int(params.get("slow_ema", 21))

        if len(closes) < 35:
            return Signal(action="HOLD", reason="Insufficient data for ADX Trend Strategy")

        adx_result = IndicatorEngine.adx(highs, lows, closes, 14)
        adx_vals = adx_result["adx"]
        plus_di_vals = adx_result["plus_di"]
        minus_di_vals = adx_result["minus_di"]

        curr_adx   = adx_vals[-1]
        prev_adx   = adx_vals[-2] if len(adx_vals) >= 2 else None
        curr_pdi   = plus_di_vals[-1]
        curr_mdi   = minus_di_vals[-1]

        fast_ema = IndicatorEngine.ema(closes, ema_fast)
        slow_ema = IndicatorEngine.ema(closes, ema_slow)
        curr_fast = fast_ema[-1] if fast_ema else None
        curr_slow = slow_ema[-1] if slow_ema else None
        prev_fast = fast_ema[-2] if fast_ema and len(fast_ema) >= 2 else None
        prev_slow = slow_ema[-2] if slow_ema and len(slow_ema) >= 2 else None

        common = self._compute_common(closes, volumes)
        rsi = common["rsi"]

        indicator_vals = {
            "adx": curr_adx,
            "plus_di": curr_pdi,
            "minus_di": curr_mdi,
            "adx_threshold": adx_threshold,
            "fast_ema": curr_fast,
            "slow_ema": curr_slow,
            "rsi": rsi,
            "macd_hist": common["macd_hist"],
            "vol_ratio": common["vol_ratio"],
        }

        if curr_adx is None or curr_pdi is None or curr_mdi is None:
            return Signal(action="HOLD", reason="ADX data not ready", indicator_values=indicator_vals)

        trend_strong = curr_adx >= adx_threshold
        adx_rising = prev_adx is not None and curr_adx > prev_adx

        # BUY: Strong uptrend — +DI leads by di_gap, EMA bullish, MACD up
        if trend_strong and curr_pdi > curr_mdi and (curr_pdi - curr_mdi) >= di_gap:
            confirmations = 0
            reasons = [f"ADX {curr_adx:.0f} — strong trend | +DI {curr_pdi:.0f} > -DI {curr_mdi:.0f}"]

            if curr_fast and curr_slow and curr_fast > curr_slow:
                confirmations += 1
                reasons.append(f"EMA{ema_fast} {curr_fast:.2f} > EMA{ema_slow} {curr_slow:.2f} (uptrend)")

            if common["macd_hist"] and common["macd_hist"] > 0:
                confirmations += 1
                reasons.append("MACD histogram positive")

            if adx_rising:
                confirmations += 1
                reasons.append(f"ADX rising — trend accelerating")

            if rsi and 40 <= rsi <= 75:
                confirmations += 1
                reasons.append(f"RSI {rsi:.0f} supports trend")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.1:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x avg")

            if confirmations >= 2:
                return Signal(
                    action="BUY",
                    confidence=min(0.60 + confirmations * 0.07, 0.95),
                    reason=" | ".join(reasons),
                    indicator_values=indicator_vals,
                )

        # SELL: Strong downtrend — -DI leads by di_gap, EMA bearish, MACD down
        if trend_strong and curr_mdi > curr_pdi and (curr_mdi - curr_pdi) >= di_gap:
            confirmations = 0
            reasons = [f"ADX {curr_adx:.0f} — strong trend | -DI {curr_mdi:.0f} > +DI {curr_pdi:.0f}"]

            if curr_fast and curr_slow and curr_fast < curr_slow:
                confirmations += 1
                reasons.append(f"EMA{ema_fast} {curr_fast:.2f} < EMA{ema_slow} {curr_slow:.2f} (downtrend)")

            if common["macd_hist"] and common["macd_hist"] < 0:
                confirmations += 1
                reasons.append("MACD histogram negative")

            if adx_rising:
                confirmations += 1
                reasons.append("ADX rising — downtrend strengthening")

            if rsi and 25 <= rsi <= 60:
                confirmations += 1
                reasons.append(f"RSI {rsi:.0f} supports downtrend")

            if common["vol_ratio"] and common["vol_ratio"] >= 1.1:
                confirmations += 1
                reasons.append(f"Volume {common['vol_ratio']:.1f}x avg")

            if confirmations >= 2:
                return Signal(
                    action="SELL",
                    confidence=min(0.60 + confirmations * 0.07, 0.95),
                    reason=" | ".join(reasons),
                    indicator_values=indicator_vals,
                )

        hold_reason = f"ADX {curr_adx:.0f}" + (" (weak trend)" if not trend_strong else f" | +DI {curr_pdi:.0f} -DI {curr_mdi:.0f} — gap too small")
        return Signal(action="HOLD", reason=hold_reason, indicator_values=indicator_vals)


# ── Singleton ─────────────────────────────────────────────────────
signal_generator = SignalGenerator()
