"""
Faculty course-builder models — subjects/courses uploaded by faculty,
approved by their Institution Admin, and scoped strictly to that institution.

Lifecycle: faculty creates a Course (status="pending") -> institution_admin
approves/rejects (status="approved"/"rejected") -> only "approved" courses
are visible to students in that institution. Super Admin can view/delete
across institutions but never approves.

Lessons may carry an uploaded material file (PDF/DOCX/PPT/MD). Assessments
hold MCQ Questions (each with Choices); questions can be added manually or
generated by AI from a lesson's uploaded material text.
"""

import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, Text, Boolean, Integer, DateTime, ForeignKey, text
from sqlalchemy.dialects.postgresql import UUID
from database.connection import Base


def _utcnow():
    return datetime.now(timezone.utc)


class Course(Base):
    __tablename__ = "courses"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    institution_id = Column(UUID(as_uuid=True), ForeignKey("institutions.id"), nullable=True, index=True)
    created_by_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)

    title = Column(String(200), nullable=False)
    description = Column(Text, nullable=True)

    # "pending" | "approved" | "rejected"
    status = Column(String(20), default="pending", nullable=False, server_default=text("'pending'"))
    review_note = Column(Text, nullable=True)
    reviewed_by_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    reviewed_at = Column(DateTime(timezone=True), nullable=True)

    # platform-wide default courses (institution_id is NULL) ship with is_default=true
    is_default = Column(Boolean, default=False, nullable=False, server_default=text("false"))

    created_at = Column(DateTime(timezone=True), default=_utcnow, nullable=False, server_default=text("CURRENT_TIMESTAMP"))
    updated_at = Column(DateTime(timezone=True), default=_utcnow, onupdate=_utcnow, nullable=False, server_default=text("CURRENT_TIMESTAMP"))


class Lesson(Base):
    __tablename__ = "lessons"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    course_id = Column(UUID(as_uuid=True), ForeignKey("courses.id", ondelete="CASCADE"), nullable=False, index=True)

    title = Column(String(200), nullable=False)
    content = Column(Text, nullable=True)  # optional plain-text notes
    order_index = Column(Integer, default=0, nullable=False, server_default=text("0"))

    # uploaded material (PDF/DOCX/PPT/MD) — one file per lesson
    file_url = Column(String(500), nullable=True)
    file_name = Column(String(255), nullable=True)
    file_type = Column(String(20), nullable=True)  # "pdf" | "docx" | "pptx" | "md"
    # extracted plain text used as AI context for MCQ generation
    extracted_text = Column(Text, nullable=True)

    created_at = Column(DateTime(timezone=True), default=_utcnow, nullable=False, server_default=text("CURRENT_TIMESTAMP"))


class Assessment(Base):
    __tablename__ = "assessments"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    course_id = Column(UUID(as_uuid=True), ForeignKey("courses.id", ondelete="CASCADE"), nullable=False, index=True)

    title = Column(String(200), nullable=False)
    instructions = Column(Text, nullable=True)
    pass_score = Column(Integer, default=70, nullable=False, server_default=text("70"))

    # config faculty sets BEFORE handing off to AI generation
    question_count = Column(Integer, default=5, nullable=False, server_default=text("5"))
    difficulty = Column(String(20), default="medium", nullable=False, server_default=text("'medium'"))  # easy|medium|hard

    created_at = Column(DateTime(timezone=True), default=_utcnow, nullable=False, server_default=text("CURRENT_TIMESTAMP"))


class Question(Base):
    __tablename__ = "questions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    assessment_id = Column(UUID(as_uuid=True), ForeignKey("assessments.id", ondelete="CASCADE"), nullable=False, index=True)

    order_index = Column(Integer, default=0, nullable=False, server_default=text("0"))
    # "ai" | "manual"
    source = Column(String(10), default="manual", nullable=False, server_default=text("'manual'"))

    created_at = Column(DateTime(timezone=True), default=_utcnow, nullable=False, server_default=text("CURRENT_TIMESTAMP"))

    # Assigned last: naming this column "text" shadows the module-level
    # sqlalchemy.text() import for any code below it in this class body.
    text = Column(Text, nullable=False)


class Choice(Base):
    __tablename__ = "choices"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    question_id = Column(UUID(as_uuid=True), ForeignKey("questions.id", ondelete="CASCADE"), nullable=False, index=True)

    is_correct = Column(Boolean, default=False, nullable=False, server_default=text("false"))
    order_index = Column(Integer, default=0, nullable=False, server_default=text("0"))

    # Assigned last: naming this column "text" shadows the module-level
    # sqlalchemy.text() import for any code below it in this class body.
    text = Column(Text, nullable=False)


class LessonProgress(Base):
    """Tracks which lessons a student has marked as read, per course."""

    __tablename__ = "lesson_progress"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False, index=True)
    lesson_id = Column(UUID(as_uuid=True), ForeignKey("lessons.id", ondelete="CASCADE"), nullable=False, index=True)
    course_id = Column(UUID(as_uuid=True), ForeignKey("courses.id", ondelete="CASCADE"), nullable=False, index=True)

    completed_at = Column(DateTime(timezone=True), default=_utcnow, nullable=False, server_default=text("CURRENT_TIMESTAMP"))


class AssessmentAttempt(Base):
    """One student's attempt at an assessment; graded immediately on submit.

    Each student may have at most one attempt per assessment unless an
    Institution Admin grants a retake (see AssessmentRetakeGrant) — that
    grant is consumed by the next started attempt.
    """

    __tablename__ = "assessment_attempts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False, index=True)
    assessment_id = Column(UUID(as_uuid=True), ForeignKey("assessments.id", ondelete="CASCADE"), nullable=False, index=True)
    course_id = Column(UUID(as_uuid=True), ForeignKey("courses.id", ondelete="CASCADE"), nullable=False, index=True)

    score_percent = Column(Integer, nullable=False)
    passed = Column(Boolean, nullable=False)
    total_questions = Column(Integer, nullable=False)
    correct_count = Column(Integer, nullable=False)

    # Proctoring — set true and force-submitted when a student accumulates
    # 3 suspicious actions (tab switch, right-click, screenshot attempt)
    # during a timed attempt.
    flagged = Column(Boolean, default=False, nullable=False, server_default=text("false"))
    flag_reason = Column(Text, nullable=True)

    started_at = Column(DateTime(timezone=True), nullable=False, server_default=text("CURRENT_TIMESTAMP"))


class AssessmentRetakeGrant(Base):
    """An Institution Admin's one-time permission for a student to retake
    an assessment they've already attempted. Consumed when the student
    starts their next attempt on that assessment."""

    __tablename__ = "assessment_retake_grants"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False, index=True)
    assessment_id = Column(UUID(as_uuid=True), ForeignKey("assessments.id", ondelete="CASCADE"), nullable=False, index=True)
    granted_by_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)

    consumed = Column(Boolean, default=False, nullable=False, server_default=text("false"))
    created_at = Column(DateTime(timezone=True), default=_utcnow, nullable=False, server_default=text("CURRENT_TIMESTAMP"))

    submitted_at = Column(DateTime(timezone=True), default=_utcnow, nullable=False, server_default=text("CURRENT_TIMESTAMP"))


class AttemptAnswer(Base):
    """One question's recorded answer within an AssessmentAttempt."""

    __tablename__ = "attempt_answers"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    attempt_id = Column(UUID(as_uuid=True), ForeignKey("assessment_attempts.id", ondelete="CASCADE"), nullable=False, index=True)
    question_id = Column(UUID(as_uuid=True), ForeignKey("questions.id"), nullable=False)
    choice_id = Column(UUID(as_uuid=True), ForeignKey("choices.id"), nullable=True)
    is_correct = Column(Boolean, nullable=False, default=False, server_default=text("false"))
